### ISSUE TITLE
Website: Session-Planning-Tool

### ISSUE THREAD

**Issue by endverbraucher** [railscamp/railscamp-germany-2014#1]
something like:
- jsunconf 2014
- froscon
- eurucamp sessions (sessions.railscamp.de)

**Comment by Uepsilon** [comment]
i'll ask which tool is used by the froscon

**Comment by Uepsilon** [comment]
Froscon is using [Frab](https://github.com/frab/frab)

**Comment by RmMsr** [comment]
Note from Meeting on 10th June: What is the current state? Do we have other candidates?

**Comment by jhilden** [comment]
@moonglum wants to look into this.  Who wants to help him?

**Comment by raucao** [comment]
The thing is, we only need a very lightweight CRUD app with basic voting. The main session management is much better on Lanyrd, where you have timetables with rooms, offline-capable web app, speaker info, coverage links, etc. – worked like a charm last year.

Maybe a RailsGirls group wants to build it?! Seems like a perfect beginner-level project.

**Comment by thegcat** [comment]
Or we could just whatever wheel was last reinvented already? http://frab.github.io/frab/ for example?

**Comment by raucao** [comment]
Why use a whole conference planning tool in addition to a whole conference planning tool?

**Comment by jhilden** [comment]
Any progress on the session planning front?  @moonglum

**Comment by jhilden** [comment]
For reference:  here is the link to the eurucamp activities app repository https://github.com/eurucamp/eurucamp-activities-2013/  and here you can see it in action http://activities.eurucamp.org/

**Comment by skade** [comment]
If you want a session planning tool, you can also use https://openspacer.org/, I can provide contact to the developer. They are currently localizing it.

**Comment by moonglum** [comment]
Sorry, I was totally out of the loop. It feels like OpenSpacer seems to be a real good fit. What do you think, @DonSchado? :smile: Could you provide me with the contact data, @skade? Would be awesome!

**Comment by skade** [comment]
Contact https://twitter.com/spr2. He's responsive and running many Barcamps. Tell him I sent you and that you need localization ;).

**Comment by moonglum** [comment]
Thank you!

**Comment by DonSchado** [comment]
:+1:

**Comment by raucao** [comment]
Please keep in mind that we only need it for submission and maybe pre-voting. Otherwise we lose all the great things that Lanyrd gives us, like the interactive timetables and offline-capable web app.

**Comment by moonglum** [comment]
Just talked Stefan on the phone. It sounds really nice as it is designed especially for BarCamps and they therefore address the requirements we have. As we are a community event, the usage of the tool is free of charge for us :wink: 
- As a user you can create sessions (Suggesting sessions that you don't want to organize is a planned feature). You can say that you are interested in an event and see everyone who's interested, too. You can also leave comments etc. You can register with email/pw, Twitter, Google or Facebook. You can try it out [here](https://openspacer.org/1-open-summit-2014).
- As an organizer you can provide information about which rooms are available and where they are etc. In the session planning tool you can then organize everything. If we want to have this information on our website, we can either do this via iFrame or calls to their API. We can of course also stay with lanyrd for that.

We also have two choices:
- Either we let everyone register on the page for the event – wether they payed or not.
- Or we say that only people that bought a ticket can get into the community. For that they can integrate with eventbrite, so this would work as well if we would prefer that. We would need to provide them with the information about people that already bought their tickets in that case of course.

I think we should do that, seems like a very good option for that. If there are no vetos, I will ask him to set it up for us. I would even say that we make it with open registration, what do you think?

**Comment by skade** [comment]
I'd also like to add that if the schedule is changing on the date, offline support is not as important as with conferences with a fixed schedule.

**Comment by jhilden** [comment]
Thanks a lot @moonglum.   Let's go with this option.  Did you already ask Stefan to set it up?

I would also definitely vote for public access, since this is a public community event.  The sooner we can start adding sessions, the better.

**Comment by moonglum** [comment]
Ok, I just emailed him – will set it up as soon as possible as an open community. Will ping when it is up.

**Comment by moonglum** [comment]
The [community is online now](https://openspacer.org/13-rails-camp-germany-2014/). Feel free to register. Step by step we will now get admin rights etc. – so I think we should wait a little longer before we unleash the people on this platform. But please take a look and see if there's something missing for us.

**Comment by raucao** [comment]
2 things about the description there:
- We got a correction changing "tent" to "camp" from a native English speaker in the meantime
- "Bike, Car, Spaceship & Hovercraft" was the headline of how to get there I believe.

**Comment by moonglum** [comment]
Ok, will change it as soon as I have admin access.

**Comment by DonSchado** [comment]
Thanks a lot @moonglum :dancers:

**Comment by RmMsr** [comment]
Looks nice. Can we already move the suggestions from #25 into it?

**Comment by moonglum** [comment]
Yes we can!

**Comment by moonglum** [comment]
Ok, if we want to embed information from the Open Spacer page, we can embed information as either an iFrame or via the HTTP JSON API they provide. I will forward you more information about that soon. I will also get the credentials for administrating the page very soon.

**Comment by erdnusskeks** [comment]
I put the link at the bottom of "contribute" - just to have it on the site. So you can already share this link: http://2014.railscamp.de/contribute

**Comment by moonglum** [comment]
Thanks!

**Comment by m20io** [comment]
I just mail with Tobias and the tool right now only support german as an interface language. But they will updated it soon. Right now we cant do support other languages if somebody asks. Also we should put a notice that sessions should be describe in english.

**Comment by moonglum** [comment]
Ok, I have full admin access now. Whoever wants that to, please ping me. I will then tell the OpenSpace people to add you :wink: 

I wanted to add the rooms to the room plan. What rooms do we have (Name, Capacity, Where to find it)?

**Comment by jhilden** [comment]
I want admin access as well.

I think we can close the issue now.
