### ISSUE TITLE
ticket sale

### ISSUE THREAD

**Issue by erdnusskeks** [railscamp/railscamp-germany-2014#10]

**Comment by endverbraucher** [comment]
/me and @m20io will create a eventbrite event and integrate this into the page.

**Comment by m20io** [comment]
You can just copy an previous event a adjust the necessary things like dates etc. [howto](http://help.eventbrite.com/customer/portal/articles/426069-how-to-copy-an-event-page)

I (@m20io) will just do it and @slogmen can double check it.

**Comment by m20io** [comment]
the event is now ready, but we still need some informations about a bank account (First name, Last name, address, IBAN, BIC) @thilo Could you help us with this?

**Comment by raucao** [comment]
See mailing list.

**Comment by m20io** [comment]
Sorry could only find the address :( 
Adalbertstr. 7-8, 10999 Berlin

**Comment by thilo** [comment]
IBAN: DE44120300001008381756 
BIC: BYLADEM1001 

Besten Gruß 

Thilo

**Comment by jhilden** [comment]
great news.  so what else needs to happen before we can sell tickets through the website?

**Comment by m20io** [comment]
I just updated the payment options. But I cant enter the complete address (streng error with eventbrite - already asked there support). Anyway the only thing that is not correct right now is the number of the house (its missing). I would suggest we put it on the website like that...

**Comment by raucao** [comment]
I just received an email from Eventbrite:

> This email is to notify you that your Eventbrite payout information for RailsCamp Germany 2014 has been changed. If this change was made without your knowledge, please give us a call: 1-800-350-8850 (US) or +1-415-694-7900 (outside of the US). 

Has the Ruby Berlin e.V. account changed since last year? I have a feeling it's just a misleading notification, because I haven't looked at whatever was done there in the meantime.

**Comment by koos** [comment]
If you need any help with Eventbrite - I’m very well connected with them. Just letting you know.

**Comment by raucao** [comment]
"Yo dawg, I put some email in your GitHub, so you can read, while you read."

**Comment by thilo** [comment]
Umstellung zu SWIFT?

Zu checken hier nochmal:

IBAN: DE44120300001008381756
BIC: BYLADEM1001

**Comment by raucao** [comment]
Ah ja, klar. Danke.

**Comment by m20io** [comment]
@slogmen could you use the code I send you?

**Comment by m20io** [comment]
This could be added this to the website :)

```
<div style="width:100%; text-align:left;" ><iframe  src="https://www.eventbrite.com/tickets-external?eid=11844129109&ref=etckt" frameborder="0" height="246" width="100%" vspace="0" hspace="0" marginheight="5" marginwidth="5" scrolling="auto" allowtransparency="true"></iframe><div style="font-family:Helvetica, Arial; font-size:10px; padding:5px 0 5px; margin:2px; width:100%; text-align:left;" ><a style="color:#ddd; text-decoration:none;" target="_blank" href="http://www.eventbrite.com/r/etckt">Sell Tickets</a> <span style="color:#ddd;">through</span> <a style="color:#ddd; text-decoration:none;" target="_blank" href="http://www.eventbrite.com?ref=etckt">Eventbrite</a></div></div>
```

**Comment by raucao** [comment]
I think it's enough to change the event ID in the existing code. That way it's safe in regards to styling etc.

**Comment by endverbraucher** [comment]
I will do this today.

**Comment by m20io** [comment]
​marvelous ​

**Comment by endverbraucher** [comment]
Sorry for the delay. The Ticket Sale is online now!

**Comment by raucao** [comment]
Don't you want to set a start date/time to something you can announce?!

**Comment by endverbraucher** [comment]
You’re right on this. ;-) I misunderstood this a little bit.

I’m right on that we currently don’t have a start date for the ticket sale?
I’ve removed the link to the ticket site till we have solved this.

**Comment by jhilden** [comment]
OK. So let's pick a date and start tweeting/announcing.  @erdnusskeks @marcel12bell how long would you need for a quick and simple announcement?    What do you think about Monday June 23?  That would give us one week.

**Comment by endverbraucher** [comment]
Monday June 23 sounds fine. If needed I also can help with the announcement.

**Comment by erdnusskeks** [comment]
Yes, let's have June 23 as start date!
I will write an announcement.

Is there anything else we could announce? 
What about the contributions tool? Do we have a decision which one will be the best for this year?

**Comment by marcel12bell** [comment]
@Denise cool.
I’ll try to get the Blogpost ready…

**Comment by jhilden** [comment]
Thanks for getting this out.

@m20io can you please add me to the Eventbrite event? (`jakobhilden@gmail.com`)

**Comment by jhilden** [comment]
btw:  the times in Eventbrite are not quite correct.  It says `Friday, September 26, 2014 at 1:00 PM - Sunday, September 28, 2014 at 4:00 PM (CEST)`.  I would suggest we say it starts Friday at 19:00 or 20:00 and goes until Sunday 17:00.  What do the other organizers think?

**Comment by m20io** [comment]
I changed the time to Friday 19:00 to Sunday 17:00 for now. If there are other suggestions please discuss :)

**Comment by m20io** [comment]
@thilo Could you add @jhilden also to the eventbrite. I cant find the option to do that.

**Comment by thilo** [comment]
@m20io do i have an account there? if yes which email? I can't find any info on that.

**Comment by m20io** [comment]
@thile sorry I though you had given me access. But is was @skddc - could you add @jhilden to the railscamp event - it seams I cant do it.

**Comment by raucao** [comment]
Yup, just need an email address (ideally of an existing account, so you don't have to log in separately).

**Comment by jhilden** [comment]
`jakobhilden@gmail.com`
