### ISSUE TITLE
Catering (food for the whole day)

### ISSUE THREAD

**Issue by erdnusskeks** [railscamp/railscamp-germany-2014#11]

**Comment by jhilden** [comment]
@tatjanala can you help with this again?

@erdnusskeks will we be able to get cake and sweet stuff from http://www.cafe-fatsch.de/ ?

Should we get the same kind of finger food again that we had last year?  Or should we do it differently?

**Comment by Uepsilon** [comment]
I got the orders from last year from @tatjanala but she said it was way to much. I'll try to adjust that. 

@jhilden which cake / sweet stuff do you like to have?

**Comment by tatjanala** [comment]
@Uepsilon if you need any help with ordering sandwiches at CafeCafe or sweets at Cafe Fatsch, let me know! I'm happy to help!

**Comment by erdnusskeks** [comment]
@jhilden: I will ask Café Fatsch for cake.
@Uepsilon: Maybe you can ask cafecafe to send two calculations (with and without cake and sweets).
Then we can compare all the costs and decide what we want.

**Comment by erdnusskeks** [comment]
Café Fatsch can't deliver cake... So, it would be best to ask cafecafe for sweet snacks, too. @tatjanala @Uepsilon: Then we need just one calculation. Makes it much easier. : )

**Comment by Uepsilon** [comment]
I just placed an Order at cafecafe, which includes sandwiches, bagels, salads and some sweets / cakes. 

I used the numbers we had last year, but reduced the amount a bit since @tatjanala said there were many leftovers. 

If someone goes hungry, call pizza taxi ;)
