### ISSUE TITLE
Drinks

### ISSUE THREAD

**Issue by erdnusskeks** [railscamp/railscamp-germany-2014#12]

**Comment by Uepsilon** [comment]
Does anybody have the bill from last year so we can see what we actually used. I think a lot of stuff went back so I guess it would be good if we try to change the amounts accordingly. Anybody from the Ruby e.V. perhaps? @thilo?

**Comment by koos** [comment]
Do we want Muehlenkoelsch. I can get there 30% off.
Jan

**Comment by Uepsilon** [comment]
30% off which price? ;)

**Comment by koos** [comment]
Normal Getraenkehaendlerpreis

**Comment by thilo** [comment]
We spend 978,77 € excl Tax on Drinks last year without coffee which was sponsored

**Comment by Uepsilon** [comment]
@thilo do you have a list of what we actually paid? I know what we've ordered, but I don't know what was left over and what was running short at the end.. Water for example was out mid second day (due to amazing sun-hours)

**Comment by thilo** [comment]
@Uepsilon 
![photo](https://cloud.githubusercontent.com/assets/8471/3701727/2b1930be-13f6-11e4-9774-bcf4abacbdad.JPG)

**Comment by jhilden** [comment]
I would vote for using the same provider than last time.  The process with them was really smooth, even though it might be a little more expensive.

**Comment by Uepsilon** [comment]
This is the same provider. They just changed names. That's what I got from the email. I guess the owner changed? Since the prices stayed mostly the same I'd stick with them too.

**Comment by Uepsilon** [comment]
since i mistakenly deleted my comment about the order, here's what i've ordered:

| Amount | Product | Size | Price (w/ VAT) |
| --- | --- | --- | --- |
| 25 | Becks Pils | 24 x 0,33l | 14,36 € |
| 10 | Wasser (ohne Kohlensäure) | 12 x 0,75l | 2,85 € |
| 20 | Wasser (mit Kohlensäure) | 12 x 0,75l | 2,85 € |
| 10 | Coca Cola | 24 x 0,33l | 11,34 € |
| 5 | Fanta | 24 x 0,33l | 11,34 € |
| 5 | Sprite | 24 x 0,33l | 11,34 € |
| 5 | Lift | 24 x 0,33l | 11,34 € |
| 20 | Club Mate | 20 x 0,5l | 12,52 € |
| 5 | Gaffel Fassbrause | 24 x 0,33 | 12,45 € |

**Comment by jhilden** [comment]
no Kölsch?  wuut!?!?

**Comment by Uepsilon** [comment]
I'm talking with @koos about Kölsch as he said he could get it cheaper.. If this failes, I'll add it ;) 

I've added you @jhilden as contact (besides me) and asked them to deliver around 6pm on Friday. 
Furthermore I've asked for a fridge-trailer

**Comment by jhilden** [comment]
We still have 19 crates of discounted Mühlenkölsch, that we can get for Railscamp.  Together with the 25 crates of Becks (or maybe we should get some cheaper/better Pils?) we should be fine on the beer side.

**Comment by Uepsilon** [comment]
Canceled the drinks at Getränke Frenzel, we'll receive the stuff from dirk (guy from @koos)

**Comment by Uepsilon** [comment]
did somebody ( @jhilden, @thilo ) receive an invoice for the drinks?
