### ISSUE TITLE
Coffee

### ISSUE THREAD

**Issue by erdnusskeks** [railscamp/railscamp-germany-2014#13]

**Comment by Uepsilon** [comment]
any feedback on the coffee from last year? i liked it and would go with the same one again. anybody got some contact details for me? 

or feel free to make proposals. if it will be as hot as last time, we could use some iced coffee, so who has some references for that?

**Comment by jhilden** [comment]
@bascht should have the contact details.  He set up the connection last year.

**Comment by bascht** [comment]
@Uepsilon @jhilden Yep - they meanwhile have a brand new site [with contact details](http://www.moxxacaffe.de/Ueber_uns/moxxa.mobil).

**Comment by Uepsilon** [comment]
Moxxa just replied to my email, telling me that they are available. Their price would be 880€. This would include all non-alcoholic coffee drinks (black, cappuccino, etc.). 

They also offer cold drinks and food which can be bought at place. I guess, since we already order that separately, we don't need that and should tell them not to bring anything else (except cantuccini ofc :ghost:)

Last chance for somebody to recommend someone else.. ;)

**Comment by jhilden** [comment]
Isn't that a lot more than we paid last year?  Who has the information on that?  @thilo @tatjanala ?

**Comment by bascht** [comment]
@jhilden @Uepsilon See last years ticket: https://github.com/railscamp/railscamp-germany-2013/issues/17#issuecomment-20687585

**Comment by Uepsilon** [comment]
Since I missed that he was talking about prices without tax, I'll just go back and talk to him again.

**Comment by jhilden** [comment]
@bascht I only had the per-day price in mind (400€/day).  For 2 days it makes perfect sense. Thanks for clarifying.

**Comment by Uepsilon** [comment]
But 880€ + Tax = 1047€, which is WAY more than last year ;)

**Comment by tatjanala** [comment]
For two days (a 8h Servicezeit Barista) and 300 coffees per day a coffee bike / mobile Kaffeebar from VanDyck costs 1330€.

Shams is evan more expensive. But Frau Nora & Herr Max is supposed to be good too. I could ask for an quotation as well. But I need some more information. For two days? How many hours and how many coffees?

**Comment by Uepsilon** [comment]
I guess we don't need 8h.. If he starts around 10:00 and closes down at 16:00 it will be more than enough time for everybody to grab at least some coffees. After that most will switch to softdrinks / mate / beer.

300 Cups seem reasonable with 140 ppl around. Or even less. 

I'll ask them.

**Comment by Uepsilon** [comment]
oh btw, last year we paid 400€ per day + tax, so It summed up to 952€

**Comment by Uepsilon** [comment]
Frau Nora & Herr Max are not available.

**Comment by Uepsilon** [comment]
Since no further request were made I've asked Moxxa to be our coffein-supplier ;) I'll update with more details once I get the recalculated price for the reduced time / amount.

**Comment by Uepsilon** [comment]
@DonSchado I've heard you talked with reputami about coffee n stuff. Need Input! Otherwise we'll end up with two suppliers.

**Comment by DonSchado** [comment]
maybe @reputamiOT has an update on this?

**Comment by RmMsr** [comment]
Coffee comes from Bambule.Kaffeebar
- Sa 9:30 - 17:30
- So 9:30 - 16:00
