### ISSUE TITLE
Venue/Abenteuerhalle

### ISSUE THREAD

**Issue by erdnusskeks** [railscamp/railscamp-germany-2014#14]

**Comment by jhilden** [comment]
I will go to the Abenteuerhallen tomorrow around 19:00/20:00 to meet with our new contact there:  Salvatore Pendolino.  In case anybody wants to accompany me.

I just want to get to know them and talk about the approach/costs for this year.

Concrete questions I want to ask are about a better setup for the internet dish that we put on the roof last year.  Any other questions I should ask?

**Comment by jhilden** [comment]
The meeting was nice last week.  We agreed on a budget and will basically do everything as we did last year.

Some notes:
- the skate hall is already rented out on Saturday 12:00-15:00 and from 15:00-22:00 there is public skating.  So we will only be able to use it until noon for sleeping.  On Sunday we could potentially use it until 15:00.  (e.g. @RmMsr was talking about maybe doing a remote controlled race car race thing).
- I plan to schedule another meeting with the Hausmeister in the comming days/weeks to figure out a better placemenet for our internet dish on the roof (FYI @badboy @eimann)
- the Abenteuerhallen have a Siebdruckwerkstatt now which means particpants would be able to print their own swag (e.g. t-shirts).  Anybody any experience with that, who would like to organize this?

**Comment by jhilden** [comment]
I will meet with the Abenteuerhalle Hausmeister next Tuesday June 24 at 10:00 to check the satellite dish situation on the roof.  If anybody else wants to see the venue you are welcome to join.

**Comment by jhilden** [comment]
Meeting with the Hausmeister was good today.   I will need to buy a couple supplies, then we should have a nice setup for the satellite dish that is higher and more stable than last time.

**Comment by eimann** [comment]
Good news, @jhilden!

**Comment by jhilden** [comment]
@eimann we might need a longer cable though, since it will on the top of the roof this time.  What length did you have?

**Comment by eimann** [comment]
I think we have 3x 70m, 4x 50m and 4x25m + couples + switches + power injectors, we just bring everything and see what we need :)

**Comment by jhilden** [comment]
I will have a meeting at the venue in the coming days again.  Here are the things on my list:
- install the base construction for the satellite dish
- check out the siebdruck room, to see what they have
- talk with them about contract stuff
- ask about contact to Sünner Brauerei (-> Bier, Kühlwagen)

Anything else you can think of, that would be important to check out at the venue?

**Comment by erdnusskeks** [comment]
Please have a look at the opportunities for the main stage. We thought about shifting it a bit - would that be possible? (regarding beamer, speakers and all the technical stuff)

**Comment by jhilden** [comment]
I will be there next wednesday (10.9.) at 11:00 Uhr, if anybody wants to come along.

**Comment by jhilden** [comment]
the meeting was good.  I created a ticket about the Siebdruck room/workshop #71 and the base construction for the satellite dish is complete (see pic),  so this year we should be a couple meters higher than last year.

![2014-09-10 12 43 21](https://cloud.githubusercontent.com/assets/69657/4220780/b4445aa8-3903-11e4-84ba-d2682f192659.jpg)

**Comment by jhilden** [comment]
Next appointment,  tomorrow (Wednesday) evening 18:00/19:00

Things to check/do:
- floor plan or dimensions for wifi setup #20 
- check for freezers and general cocktail sitation
- hopefully meet with coffee supplier to talk about setup
- contract
- talk about the setup construction for the heavy projector
- maybe discuss details about siebdruck workshop (@mwollenschlaeger ?)
