### ISSUE TITLE
finance/accounting/budget

### ISSUE THREAD

**Issue by erdnusskeks** [railscamp/railscamp-germany-2014#16]

**Comment by thilo** [comment]
Current budget plan is here: https://docs.google.com/spreadsheet/ccc?key=0AtZxiTQL2ah_dE5SaXdNQzlmai0wUXhDUTlMOWh0VHc&usp=drive_web#gid=1

**Comment by thilo** [comment]
in regards to accounting/invoicing we can use the harvest account of the Verein https://rubyberlin.harvestapp.com. Or what do you intent to use?

**Comment by RmMsr** [comment]
@thilo It would be great if we could use the invoicing of the Ruby e.V. But I don't know Harvest in particular. As I am involved in sponsoring anyways I could help with processing the data or provide you with everything you need.

BTW: Do we add Taxes to the sponsoring packages? What rate?

**Comment by thilo** [comment]
@RmMsr sponsorships have 19% ( always charge 19% when in doubt) Would be great if you take care of invoicing sponsors. harvest is straight forward. provide me a save channel to send you the login details. Are you also the contact for sponsoring at railscamp?

**Comment by RmMsr** [comment]
@thilo Yes, I am working on sponsors along with @m20io. You could encrypt the credentials using https://github.com/twe4ked/catacomb and use my github email. If you prefer I can provide you a PGP or S/MIME key or something else?

**Comment by thilo** [comment]
@RmMsr das tool spuckt bei mir ne fehler aus, bevor ich jetzt noch lang rumprobiere sendem mir doch einfach deinen PGP public key.

**Comment by RmMsr** [comment]
@thilo All right. I guess that would be the 256 Bytes limit. You find [my gpg public key](http://keys.gnupg.net/pks/lookup?op=get&search=0xC8945357CBE4D9E9) on the keyservers.

**Comment by thilo** [comment]
@RmMsr großartiger UI fail, die daten sind dir gerade versehentlich unverschlüsselt zugegangen. eine zweite verschlüsselte email mit neuem passwd folgt.
