### ISSUE TITLE
DNS setup

### ISSUE THREAD

**Issue by endverbraucher** [railscamp/railscamp-germany-2014#17]
Sebastian,

could you please setup DNS for 2014.railscamp.de? (Same procedure as every year, we are going to recycle the website of the last railscamp ;-)

thanks!
thomas

**Comment by raucao** [comment]
Where do you want me to point it? GitHub pages?

**Comment by endverbraucher** [comment]
correct. Github pages.

**Comment by raucao** [comment]
Done.

![screen shot 2014-05-14 at 17 45 13](https://cloud.githubusercontent.com/assets/842/2973554/c7f7f57e-db7e-11e3-939c-4cd5eba2f3af.png)

**Comment by jhilden** [comment]
Can this be closed?
