### ISSUE TITLE
Finding a date

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2014#18]
I wrote to the Abenteuerhallen last week and again today.  Wednesday evenings they always have their team meeting and I hope to hear from them after that.

Again, here are the potentially possible dates, in prioritized order:
1. 26-28 Sep
2. 30-31 Aug
3. ~~15-17 Aug~~

**Comment by raucao** [comment]
+1 for end of August, because summer. :)

(My birthday is on Sep 25 and it has an abysmal track record of shitty weather).

**Comment by jhilden** [comment]
Only problem is that Froscon will be August 23-24, and most probably will also have a Ruby track https://twitter.com/RedFrogConf

More feedback is very welcome.

**Comment by raucao** [comment]
Sounds perfect to me. Wanted to go there anyway. :)

**Comment by tisba** [comment]
+1 end of August

**Comment by endverbraucher** [comment]
+1 end of September

**Comment by martinotten** [comment]
+1 September

**Comment by jhilden** [comment]
I got Feedback from the Abenteuerhallen:   The weekend August 15-17 is out, but we could have the other 2 weekends August 29-31 or September 26-28.  I told them that we would decide on the next orga meeting which will be next Tuesday May 20 at 18:00 on Google Hangout or at the Railslove Office.

So, let the feedback keep coming

**Comment by jhilden** [comment]
Trying to summarize the pros & cons here:

| August 29-31 | September 26-28 |
| --- | :-: |
| moar summer | moar time to organize |
|  | better spacing to other ruby events |
|  |  |

**Comment by raucao** [comment]
Yay, I'll be at the Railslove office.

**Comment by jayeff** [comment]
+1 September

**Comment by erdnusskeks** [comment]
+1 September

**Comment by Uepsilon** [comment]
+1 September

**Comment by m20io** [comment]
+1 September

**Comment by RmMsr** [comment]
+1 September

**Comment by DonSchado** [comment]
so september it is :dancers:

**Comment by jhilden** [comment]
I will talk to the Abenteuerhallen asap and fix the date in September.

**Comment by jhilden** [comment]
The date is confirmed.  Closing this issue.
