### ISSUE TITLE
Feedback-Board

### ISSUE THREAD

**Issue by endverbraucher** [railscamp/railscamp-germany-2014#19]
We should have a feedback board like jsunconf had one. This would be a good place for people to leave some feedback on the event. Would anyone organize this?

(Btw, we’re talking not about a digital board here ;-)

**Comment by RmMsr** [comment]
I was not at this event, but I like the idea. I guess it's a big white paper?

**Comment by m20io** [comment]
We could use some Post-Its to gather the feedback - then we dont need to
carry around the big paper sheets.

**Comment by raucao** [comment]
It was a board with sheets already attached to it, so you could just grab a marker and start writing something.

**Comment by RmMsr** [comment]
Where do we get a board? Or do we just pin paper to a wall?

I remember the venue had at least one, but no paper last year

**Comment by m20io** [comment]
Lets just tape a rectangel and pin/tape paper sheets to the wall.

**Comment by jhilden** [comment]
that sounds like a very Railscamp-DIY-kind of solution @m20io :thumbsup:

Does any of the sponsors by chance have branded pens and post-its, that could be used?

**Comment by badboy** [comment]
Also: let's tape that ~3-4 meters above the ground, so people have to climb for feedback! (sorry for this totally useless comment)

**Comment by jhilden** [comment]
I like it.   The area for positive feedback can be on ground level though ;)
