### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2014#20]
We will need equipment and people to set it up.

@thilo can you tell us exactly what kind of equipment the Ruby e.V. has bought and how we would be able to use it (shipping, etc.)?

@timbuchwaldt @zakx would you be willing to work your magic again this year?

**Comment by zakx** [comment]
Habe WLAN-Equipment beim CCC angefragt.

**Comment by thegcat** [comment]
Zur Info: [Planio](http://plan.io) hat WLAN Hardware (6 [Ubiquiti Unifi](http://www.ubnt.com/unifi)), die wir gerne an Ruby/Rails Events verleihen. Die sind schon beim EuruCamp 2013 und PMCamp 2013 erfolgreich zum Einsatz gekommen.

**Comment by thegcat** [comment]
(Disclaimer: Ich arbeite für Planio. Die Hardware würde ich dann mitbringen und ggfs. an @badboy et. al übergeben, falls die sich auch um die WLAN-Seite des Netzes kümmern möchten)

**Comment by zakx** [comment]
@thegcat Was für Unifis sind das genau?

**Comment by thegcat** [comment]
Schaue ich gleich wenn ich in Berlin bin :-) :train2:

**Comment by koos** [comment]
Wir haben 3 Unifis

**Comment by thilo** [comment]
Wir haben im Verein. 3 Unifi AC mit 3.1.13 FW, einen 5 Port POE EdgeRouter und den 8 Port POE ToughSwitch und ne halb volle trommel mit ethernet Kabeln. @thegcat würdest du ggf auch Kurrier für o.g. HW übernehmen?

**Comment by timbuchwaldt** [comment]
Sollten wir das EventWLAN wie geplant vom CCC-MZ bekommen würde ich das stark bevorzugen. Die Dinger können wir einfach an die Decke Tapen, haben alle Kabel, Switches und Server direkt dabei. @zakx und ich würden die WLAN-Seite machen, rrbone die WAN-Seite mit Funkstrecke.

**Comment by zakx** [comment]
CCC hat zugesagt, wir bekommen das Event-WLAN. Damit brauchen wir keine sonstigen Leihgaben.

**Comment by jhilden** [comment]
@zakx thanks a lot for arranging this.  How will shipping be handled this year?  I think last year the return of the equipment to Mainz was a little last-minute.  We should organize this better this year.  Any takers?

**Comment by RmMsr** [comment]
What are the options here in terms of measurements? Sending a parcel, carrying a box, pack it in a car?

**Comment by zakx** [comment]
![20130312_171725](https://cloud.githubusercontent.com/assets/628602/3501506/4166d9da-0617-11e4-9535-996796e63e7a.jpg)

So, parcel is still an (expensive) option. The box is most likely somewhere around 20kgs.

**Comment by timbuchwaldt** [comment]
Car works good, did that last year (had to go to MZ anyway).

**Comment by RmMsr** [comment]
Our reservation is visible in the calendar: https://eventwlan.cccmz.de/reservierung/?cid=all&month=9&yr=2014

Does anyone know somebody to fetch the equipment for friday?

**Comment by timbuchwaldt** [comment]
I trust @zakx to make it magically appear again :D Worked well last time IIRC.

**Comment by jhilden** [comment]
What does @zakx say?

Or does anybody know anybody who will travel through Mainz to the Railscamp?

@designhunger are you coming to the camp (--> 2014.railscamp.de)?  Or do you know anybody from Mainz who might?

**Comment by zakx** [comment]
Like last year, I'll arrange transport TO railscamp. You will need to take care about getting the stuff back to Mainz AFTER the event.

**Comment by designhunger** [comment]
I'll be in Spain to that time... Maybe the guys from Crispy Mountain can take care of it.

**Comment by tr37ion** [comment]
In addition to this topic, we could ask the www.freenet.net people to show their project at this event, too.

**Comment by zakx** [comment]
Update: I was looking to take the hardware with me after this weekends' event, but sadly there's another conference in between so this isn't possible this year. Therefore someone would need to pick it up in Mainz or we'll have to arrange some other form of transport. (See https://eventwlan.cccmz.de/reservierung/)

**Comment by jhilden** [comment]
Does anybody know anyone coming through Mainz?  Spread the word:  https://twitter.com/railscamp_de/status/508898681735503872

**Comment by jhilden** [comment]
@benedikt are you coming to Railscamp?  Or do you know anybody who is coming to the camp from your part of Germany?

**Comment by benedikt** [comment]
@jhilden Sorry, I won't make it this year :cry: and unfortunately don't know of anyone local who's going. I'll ask around, though.

**Comment by jhilden** [comment]
@cweyer @jgarth @jtreitz @maprinz we are still looking for devs from Mainz that want to come to the Railscamp in 3 weeks and could possibly bring along the wifi equipment from the CCC MZ.  @designhunger mentioned above that you could be potential candiates.

**Comment by jhilden** [comment]
looks like the CCC EventWLAN ist not coming from Mainz but from Berlin.  It will be used this weekend near the O2 world and could be delivered on Sunday (21.9.) to any place in Berlin.

Who from Berlin would be able to arrive on Friday during the day and could take this box along?

![](https://cloud.githubusercontent.com/assets/628602/3501506/4166d9da-0617-11e4-9535-996796e63e7a.jpg)

@bitboxer? @thilo? @grekko? @skddc? Who else is coming from Berlin?

@zakx @timbuchwaldt what would be the minimum time that the equipment should arrive on Friday to allow enough time for the setup?

**Comment by bitboxer** [comment]
I arrive on 26.09 at 11:09 in Cologne Main Station with the Berlin Ruby
Train(TM).

If this is enough for you, I could bring it with me. But I would love if
someone would pick me up from the main station with that box, if that is
possible.

Bodo

**Comment by jhilden** [comment]
Thanks a lot @bitboxer 

I'm pretty sure that ~11:30 should leave enough time for @zakx and @timbuchwaldt or?

Pickup from the train station should definitely be possible.  Volunteers from Cologne with a car please raise your hands.

**Comment by bitboxer** [comment]
Can you give the CCC person my contact details? 

Bodo Tasche, +49 1512 7533048, Richard-Sorge-Str. 58 .

Important: the entrance is a little bit hidden. It is marked with a red pin on this Photo:

![adresse](https://cloud.githubusercontent.com/assets/56195/4286026/679294ba-3d8e-11e4-9ee7-c4f14c3b2455.jpg)

**Comment by bitboxer** [comment]
And it would be awesome If I could get an aprox delivery time on Sunday to make absolutely sure that I am at home :wink: .

**Comment by bitboxer** [comment]
The CCC EventWLAN is now in my apartment. Will bring it on Friday.

**Comment by jhilden** [comment]
Thanks a lot @bitboxer 

@zakx @timbuchwaldt so the EventWLAN should be at the Abentuerhallen at around 11:30ish on Friday (if the train is on time).  Do we have a plan for the wifi setup?

As mentioned via email, there won't be any network cables coming with the EventWLAN this time.  What should we do about this?  Any suggestions where we can get cables?  How much would you need?  Would be nice if you could contact me about this.

**Comment by eimann** [comment]
Who brings what? Only the CCCMZ Event WLAN? This would be eight indoor APs and one outdoor AP.

2x 10m Cat6 cable with Hirose TM21, 20EUR/ea. (2x Indoor AP)
3x 20m Cat6 cable with Hirose TM21, 35EUR/ea. (3x Indoor AP)
3x 40m Cat6 cable with Hirose TM21,  55EUR/ea. (3x Indoor AP)
2x 80m Cat6 cable with Hirose TM21, 100EUR/ea. (Outdoor AP + Internet Uplink)

This is around 510EUR only for cables.
A floorplan of the Abenteuerhallen would help to measure the cable length and AP placing.

**Comment by zakx** [comment]
From last years experience, we will be fine with 4 APs (3x indoor + 1x outdoor). Most likely we'll only need 3x 20m (APs on bridge upstairs), 2x 40m (CAT6 for speakers and AP nearby) and the mentioned 2x80m (Outdoor AP + Uplink).

I do have some 500m CAT6 cable leftovers from another event (partly already cut in usable length with CAT6 sockets on each end). They are stored in Nippes at Dingfabrik. If somebody can provide transport (@badboy?) we can grab it from there. Should also have a few CAT6 sockets left over. In that case we'll also need a few short patch cables @eimann, but should overall be way cheaper than buying cables.

**Comment by jhilden** [comment]
Sounds very good @zakx.  If transportation with @badboy should not be possible, we can certainly arrange for something.

How many short patch cables do you need?  (Could probably also bring a few from our office)

**Comment by zakx** [comment]
I guess we'll need at least 12 (everything from 0.1-1m should be fine).

**Comment by jhilden** [comment]
@zakx I can bring along around 10-12 cables.  Is there any way to get some more until tomorrow?

Could you maybe call me sometime today, then we can also talk about transportation. My number ist 0174/2760218

Anything else we need?
