### ISSUE TITLE
Audio equipment

### ISSUE THREAD

**Issue by RmMsr** [railscamp/railscamp-germany-2014#21]
Is there a need to get additional audio equipment? The venue offers a sound system including 2 wireless microphones and 2 headsets. See [last year meeting notes](https://github.com/railscamp/railscamp-germany-2013/wiki/MeetUp-Notes:-2013.railscamp.de---Audio-&-Video)

[Last year issue #3](https://github.com/railscamp/railscamp-germany-2013/issues/3)

**Comment by jhilden** [comment]
@railsbros-dirk do you remember that we were missing anything important last year?  Anything that didn't work perfectly?
And by the way, @railsbros-dirk would you maybe be willing to take care of the audio stuff again this year?

**Comment by code-later** [comment]
No, I don't remember we missed anything last year. The venue was pretty well equipped and the team was very professional. Unfortunately I cannot guarantee I can attend this year thus I don't want to take over any responsibilities.

That said I think there is no need to take care of this issue in a dedicate manner. Just let the venue take care of everything.

**Comment by RmMsr** [comment]
Ok, great. So we should keep in mind that one or two people should receive an instruction how to handle the mics etc.

Hope you can make it to the RCG anyway :)
