### ISSUE TITLE
misc. data from last event for blogpost

### ISSUE THREAD

**Issue by marcel12bell** [railscamp/railscamp-germany-2014#22]
@jhilden is there a list of participants with gender/country etc. for little dataviz?
@all other data aside from lanyrd (number of tracks/length) and ideas are welcome...

**Comment by jhilden** [comment]
According to Eventbrite we had 126 participants last year.   I sent you a list with names and the IP location from where they ordered their ticket via email.  Looking forward to your analysis.

**Comment by unimatrixZxero** [comment]
Wasn't there also a Funky-Monkey-Card tracking thing going on at several locations. That might also be fun to see.

**Comment by koos** [comment]
We can use the funky monkey system and/or hack something with ibeacons or so…

**Comment by jhilden** [comment]
@marcel12bell can we still hope for something here?  If we don't publish something now, I guess it will be too late for this year's event.

**Comment by marcel12bell** [comment]
Almost finished.

**Comment by jhilden** [comment]
Thanks for your nice and personal post @marcel12bell   -->  http://2014.railscamp.de/news/2014/08/18/my-first-rails-camp.html

Closing this ticket now.
