### ISSUE TITLE
Something special on Friday?!

### ISSUE THREAD

**Issue by erdnusskeks** [railscamp/railscamp-germany-2014#23]
Some of you might know Bunte Burger. It's a mobile burger grillerei from Cologne. I had the idea to have them at the Abenteuerhallen on Friday. @Mobbit and I would love to have them there - because it's all vegan and really tasty! : )

Speaking of Friday: What about having a party? Wasn't it already planned for last year? But I don't remember a party (or I just missed it). Party is not a must-have, but it would be nice to have something special for those who already arrive on Friday - something like Bunte Burger! : )

Any opinions, ideas, additions?

**Comment by jhilden** [comment]
+1 for Bunte Burger.  I (as a omnivore) found them quite tasty as well.

However, I personally don't think we should worry too much about Friday.  Some people will only arrive on Saturday, so we should plan those 2 days first, and worry about Friday when everything else is done.   Is there any feedback about last years pre conference warm up evening?

**Comment by eimann** [comment]
I would like to see Bunte Burger around too.

**Comment by martinotten** [comment]
+1 :)

**Comment by RmMsr** [comment]
+1 for Bunte Burger
I imagine some kind of entertainment during / after buildup would be nice. But I have no concrete ideas yet.

**Comment by jhilden** [comment]
We can always go climbing or play some soccer/basketball.

Can somebody contact Bunte Burger and ask them under what conditions they would come?  (I would suggest that we start planning for participants to buy their own Burgers and consider paying for them if we find enought money/sponsoring)

**Comment by erdnusskeks** [comment]
I will send them a request.
Could you please tell me how many people arrived on Friday last year? Just
a rough number. Thanks!

2014-06-17 18:07 GMT+02:00 Jakob Hilden notifications@github.com:

**Comment by jhilden** [comment]
Hard to tell.  I would guesstimate maybe 50%,  so maybe 40-100 people.  But it's also the question if all of them would want to eat something.  Just ask them what their minimum is and we will see if it makes sense.

**Comment by erdnusskeks** [comment]
Ok, I will do!

2014-06-18 10:17 GMT+02:00 Jakob Hilden notifications@github.com:

**Comment by erdnusskeks** [comment]
Here's Bunte Burger's answer:

"Freitags stehen wir immer bis 18h auf dem Ökomarkt am Severinskirchplatz, d.h. wir könnten frühestens um 19h vor Ort sein und dann ab 19:15 oder 19:30h brutzeln.
Ab wann treffen denn die ersten Leute mit Hunger ein?

Wir haben uns 50 Burger als Minimum-Grenze gesetzt. Darunter lohnt der Aufwand nicht wirklich. Am Rheinauhafenfest hast du den Charity Burger bekommen. Hat er dir denn geschmeckt? Wir bieten den nämlich immer gerne bei solchen Veranstaltungen an, weil man dadurch die Komplexität reduziert und die Leute viel schneller an ihren Burger kommen.
Wenn du weißt, wer schon am FR Abend kommen wird und wenn diese Leute eine Vorbestellung aufgeben könnten, dann wäre die Planung deutlich einfacher."

I think the time is fine. And the Charity-Burger was really tasty!
What about reservations? How could we handle that?

One idea: Bunte Burger will be a session and everyone who wants to eat a burger joins that session. So everything depends on that glorious session tool we are all waiting for! ; )
I could ask for reservations in the next newsletter and lead the subscribers directly to the tool.

Is there a possibility to contact the people who have already bought a ticket? Does Eventbrite collect the e-mail addresses?

**Comment by erdnusskeks** [comment]
Could anyone please ask the folks from AbenteuerHallen if we need special permission for the burger truck? I have been there at Veggie Markt and saw the burger truck parking in front of the hall. Maybe it's ok to stand there but I'm not sure.

**Comment by jhilden** [comment]
I don't see a problem with this.  And if it should be the truck can always park in the private yard behind the Abenteuerhallen.  Maybe that would be nicer in generel.  Not sure.

**Comment by RmMsr** [comment]
Besides the built up we could announce a hackathon - just in case someone happens to feel uncomfortably idle.

**Comment by jhilden** [comment]
@erdnusskeks the Abenteuerhallen told me that it would be better if the truck would park in their backyard, because in front it is all restricted parking and it would also be difficult to distinguish camp participants from non-participants.  Can you pass on that information?

This is where they would need to go:  https://www.google.de/maps/place/50%C2%B056'06.1%22N+7%C2%B000'30.2%22E/@50.935036,7.008392,153m/data=!3m2!1e3!4b1!4m2!3m1!1s0x0:0x0?hl=en
We just need to make sure to open the gate.

**Comment by erdnusskeks** [comment]
No problem, I will tell the burger guys.
