### ISSUE TITLE
Logo for rubyberlin.org site

### ISSUE THREAD

**Issue by thilo** [railscamp/railscamp-germany-2014#24]
I like to put and ling to the project from the RubyBerlin site, would be nice if I can get a logo.

**Comment by jhilden** [comment]
Here is the flame logo as transparent PNG:  http://2014.railscamp.de/img/flame_500.png

And here is the flame + title on white background:   https://screencloud.net/v/eNGS

**Comment by RmMsr** [comment]
@thilo Does that fit your needs?

**Comment by thilo** [comment]
@RmMsr I thought its ok, but svg would be better :)

**Comment by RmMsr** [comment]
That's true. But it seems nobody knows if there is a vector version or who created this Railscamp logo. o_O

**Comment by raucao** [comment]
I created it. And yes, there's a vector. :)

I'll try to find it in my backups tomorrow.

**Comment by raucao** [comment]
Here it is:

https://storage.5apps.com/basti/public/shares/140709-1357-railscamp-logo.zip
