### ISSUE TITLE
Session ideas

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2014#25]
Until we have a real session planning tool we can collection session ideas here:
- http://www.buerogolf-deutschland.de/
- remote control car racing
- Siebdruckworkshop

**Comment by p886** [comment]
- Build your first command-line-application with Ruby

**Comment by raucao** [comment]
- Ember, yo!

**Comment by Malwine** [comment]
- How to take sketchnotes on tech talks.

**Comment by ghost** [comment]
- workshop: arduino-sensor-cloud-gondola

**Comment by RmMsr** [comment]
Session Ideas can now be entered into the session planning tool: https://openspacer.org/13-rails-camp-germany-2014/

@p886 @skddc @Malwine @lennartba
