### ISSUE TITLE
Outdated site http://railscamp.de/

### ISSUE THREAD

**Issue by RmMsr** [railscamp/railscamp-germany-2014#27]
It currently leads to an very outdated mixxt community. Can we redirect to `2014.railscamp.de`?

**Comment by jhilden** [comment]
@skddc you have access to the DNS, or?

**Comment by phoet** [comment]
jip, that's kinda confusing

**Comment by raucao** [comment]
Enabled forwarding, will take a bit to update caches.

**Comment by phoet** [comment]
:heart_eyes_cat: thx!

**Comment by raucao** [comment]
Works.
