### ISSUE TITLE
Marketing

### ISSUE THREAD

**Issue by marcel12bell** [railscamp/railscamp-germany-2014#29]
Like last year, let's go and do some marketing.

Here are some potentially worthwhile things to try:
email/twitter to ruby usergroups
write to the main ruby news outlets: rubyflow, ruby weekly, ruby5, ...
invite other rubyists personally
do some marketing in our neighbor countries: netherlands, belgium, poland, france, switzerland, austria, ...
Any other ideas are welcome!

what I did so far:
Post on: 
https://www.ruby-forum.com/topic/5014057#1150688
https://plus.google.com/117385509303644635034/posts/X4JmyR6mMKE
https://plus.google.com/117385509303644635034/posts/FypBavFpnD9

**Comment by badboy** [comment]
I translated it and posted it in the German Ruby Forum: http://forum.ruby-portal.de/viewtopic.php?f=12&t=26472

**Comment by marcel12bell** [comment]
@badboy thanks for translation! I used it for the german g+ forum:
https://plus.google.com/117385509303644635034/posts/Z2wJESGs2aP
https://plus.google.com/117385509303644635034/posts/7KciqRkUyBr

I asked UGs in Bremen, RUGSaar, Karlsruhe, Berlin, Hamburg, Leibzig,Dresden to spread the message...

**Comment by jhilden** [comment]
any more ideas for marketing?

@rmmsr might make a little ligthning talk / presentation @eurucamp, that's certainly a good idea.

what else could we do?

**Comment by erdnusskeks** [comment]
Here is the press release / Pressemitteilung (german and english version).
https://www.dropbox.com/sh/4ihudxibpdoa6wq/AABcZGVfy-r-fS-R-AE0tvfXa
If you want to use it just change the date.

**Comment by erdnusskeks** [comment]
There will be an interview on http://community.oreilly.de/blog.
One question I want to share with you:
Was war beim letzten RailsCamp die abgefahrenste Session? / What was the most freaky session last year?
Looking forward to reading your answers!

**Comment by jhilden** [comment]
The freakiest session was definitely the BMX riding and the broken teeth it caused ;)

**Comment by erdnusskeks** [comment]
Here you can find a draft of the next newsletter: https://www.dropbox.com/s/mrqo4qkehsuvlrk/newsletter_04.doc?dl=0
Any additions? If not I will send it tomorrow via MailChimp.

**Comment by jhilden** [comment]
Sounds really good.  Thanks for the great work @erdnusskeks 

small correction:  "more easy" -> "easier"

make sure that all the relevant pieces are properly linked (e.g. when you mention individual sessions)

I think we should say that we are really **urgently** looking for sponsors (a few thousand € short) and that we otherwise might not be able to offer certain perks, like free drinks.  A link to the current sponsors page would also be good and you can mention that sponsoring starts at only 250€.  Not sure about the final wording, but you get what I mean.

**Comment by marcel12bell** [comment]
@erdnusskeks looks fine... 
somehow i don't know if  "recognize" is the right wording in  "Did you recognize the screen printing" ... (better: find, saw?) same with "amounts" in "planning the amounts more easy". ("planing easier" works for me too)

**Comment by erdnusskeks** [comment]
... more easy - _ouch_ ... : /

Thanks for your notes. I changed the text and will send it soon to all subscribers.

**Comment by erdnusskeks** [comment]
Support for the Felt Ruby session: DaWanda will take care. ; )

Langen Nacht des Selbermachens
DaWanda macht Werbung:
Über den ganzen Monat September werden wir die Events stark bewerben und Gäste zu den Veranstaltungen einladen. Es werden Newsletter verschickt, über Facebook und Twitter werden wir aufmerksam machen und im DaWanda-Blog berichten.

Presse: 
In der Zeitschrift und den Social Media-Kanälen von burda style wird ebenso Werbung gemacht und einige lokale Zeitungen werden ebenfalls berichten. Unsere Partner idee. Creativmarkt, Marabu und Schachenmayr machen ihre Kunden ebenfalls auf die Lange Nacht des Selbermachens aufmerksam.
