### ISSUE TITLE
link to website in github home

### ISSUE THREAD

**Issue by phoet** [railscamp/railscamp-germany-2014#30]
kthxbye

http://2014.railscamp.de/
http://2014.railscamp.de/
http://2014.railscamp.de/
http://2014.railscamp.de/
http://2014.railscamp.de/
http://2014.railscamp.de/

(good for google as well)

**Comment by stuntguy3000** [comment]
?

**Comment by phoet** [comment]
[this page](https://github.com/railscamp/railscamp-germany-2014) does not contain a link to the railscamp website!

**Comment by raucao** [comment]
Fixed.

**Comment by phoet** [comment]
:+1: thx!
