### ISSUE TITLE
joint sponsorships with eurucamp/railscamp

### ISSUE THREAD

**Issue by thilo** [railscamp/railscamp-germany-2014#31]
I don't know if that was discussed already with anyone here. so I better ask. last year we offered a 10% discount to joint sponsors. We like to keep it that way again this year. cc @jhilden @erdnusskeks

**Comment by jhilden** [comment]
sounds good.

**Comment by RmMsr** [comment]
Okay. We will offer it

**Comment by thilo** [comment]
cool. here are the list of sponsors of eurucamp so far:
- soundcloud
- planio
- travisCI
- GitHub
- thoughtworks
- crealytics
- infopark

**Comment by RmMsr** [comment]
Joint sponsors so far:
- planio
- BitCrowd
