### ISSUE TITLE
Code of Conduct of Ruby Berlin e.V.

### ISSUE THREAD

**Issue by RmMsr** [railscamp/railscamp-germany-2014#36]
In the mailinglist the question arised why we not use the coc of the Ruby e.V. I like that idea.

https://github.com/rubyberlin/code-of-conduct

**Comment by moonglum** [comment]
I also like it. :+1:

**Comment by eljojo** [comment]
:+1:

**Comment by jhilden** [comment]
I'm also in favor and we are open for pull requests.  But unfortuntely none of the core organizers has time for this right now.  Who wants to help?
