### ISSUE TITLE
Donation receipt

### ISSUE THREAD

**Issue by RmMsr** [railscamp/railscamp-germany-2014#37]
We were asked if we could give out a donation receipt for multiple ticket purchases.
1. Can we give receipts so that they are tax relevant for Germany?
2. What would be the amount? The payed sum or our 'cut'?

@thilo Do you know more?

**Comment by thilo** [comment]
you can't give out donation recipes for tickets. a donation is without any expected return. you could argue that we ask for donation as you can attend the camp without paying (is this right?), than we have to provide everyone with a receipt over the full amount. maybe we should use betterplace as a middleman, they can take care of individual receipts.
