### ISSUE TITLE
create newsletter with mailchimp

### ISSUE THREAD

**Issue by endverbraucher** [railscamp/railscamp-germany-2014#4]
Goal:   Create a "railscamp_de" newsletter to inform all the potentially interested people with progress and useful information about the event
- [ ] import emails from last years attendees
- [ ] broadcast that the newsletter exists and that everybody that's interested should sign up
- [ ] integrate a signup form on the new website

**Comment by jhilden** [comment]
@Mobbit I sent you the exported list of attendees from last year.  closes #3

**Comment by martinotten** [comment]
- [x] import emails from last years attendees
- [ ] broadcast that the newsletter exists and that everybody that's interested should sign up
- [x] integrate a signup form on the new website

**Comment by martinotten** [comment]
Which reply to address can we use?

**Comment by jhilden** [comment]
I think it would be great if somebody or a group of a few people would feel responsible in case people reply to newsletters.

I would say start with a personal email address of that person and then either create a google account and/or ask @skddc if he maybe can setup a forwarding email like `newsletter@railscamp.de`

**Comment by raucao** [comment]
We do have an email address, and I believe I forwarded the webmail login last year. It's mail@railscamp.de – ping me on IRC for login credentials.

**Comment by raucao** [comment]
I also used that one for sponsor communication.

**Comment by erdnusskeks** [comment]
The newsletter is nearly ready for delivery.
But I need a mailing address (MailChimp says: "It's required by law.").
It is Martin's account, so he named his private address. But he would be happy if we used another one.
I suggest to use the address from Ruby Berlin e.V. (Adalbertstr. 7-8, 10999 Berlin).
Would it be ok for you, @thilo?

**Comment by thilo** [comment]
@erdnusskeks yes feel free to use the info@rubyberlin.org email.

**Comment by erdnusskeks** [comment]
Sorry, I meant "Postadresse". They need street, town, zip code. 
We already have a mail address (mail@railscamp.de).

**Comment by jhilden** [comment]
Awesome.  Thanks a lot @erdnusskeks 

In my opinion the general approach with this event should be "Don't ask for permission, ask for forgiveness".    This is **our** event, so just do it the way you think is best.  All the people involved are super nice, so don't be afraid that something might not be "ok".  Just do it.  Do it publicly / notify people.  And be ready to revert it, if it's a problem for anybody.  Does that sound reasonable?

**Comment by thilo** [comment]
@erdnusskeks  fine too, agree with what @jhilden said :) we are all reasonable :)

**Comment by erdnusskeks** [comment]
Ok, great - thanks! Newsletter will be sent at 6:00 pm. : )

**Comment by RmMsr** [comment]
I guess we can close this? (again)
