### ISSUE TITLE
BBQ

### ISSUE THREAD

**Issue by erdnusskeks** [railscamp/railscamp-germany-2014#44]
Who will take care of the BBQ on Saturday? @schorsch, will this be under your command like last year? : )

**Comment by jhilden** [comment]
@schorsch could you please check one of the following:
- [x] yes
- [ ] no
- [ ] maybe

Otherwise we need to find somebody else, or cancel the BBQ if worst comes to worst.

**Comment by schorsch** [comment]
Yes i'll be sponsoring the Rostbrätl - BBQ!
Depending on the head count, i can spend 200 - 300 €

refs https://github.com/railscamp/railscamp-germany-2013/issues/10#issuecomment-20968508

**Comment by jhilden** [comment]
That's really awesome news!

Will you also help with organisation/shopping for the BBQ?  @galfert are you going to be in as well?

Does anybody have an idea what the cost for the remaining BBQ stuff was last year?  In last years ticket the estimate was "380-450 €".

**Comment by schorsch** [comment]
@jhilden Please check with tatjana as she handled the bills from the handelshof.

I would need one Person to assist with the shopping. I have a car and would go a day before we start. This way we have enough time to prepare the meat. There is a big cooling room at the location so we dont need to worry.

**Comment by galfert** [comment]
At the moment it looks like I can't even make it to Railscamp this time :(

But I can write down some easy to prepare recipes for vegetarians for the BBQ for you.

**Comment by RmMsr** [comment]
Can we reuse the shopping list from last year? @tatjanala maybe?

**Comment by Uepsilon** [comment]
@schorsch I'm willing to assist you, depending on when you wan to go :smiling_imp:. Friday afternoon?

**Comment by tatjanala** [comment]
I can provide you with the handelshof receipt from last year if it helps?! @RmMsr

**Comment by RmMsr** [comment]
@tatjanala No, thanks. Thats fine.

So we just need help on site to actually do the BBQ

**Comment by Uepsilon** [comment]
i'll lend a hand

**Comment by schorsch** [comment]
Sorry for the late reply: I'll do the shopping today afternoon with tatjana.
I do need some assitance for preparing the Rostbrätl tommorrow late afternoon around 18:00

**Comment by jhilden** [comment]
I'm sure you should be able to find some helpers tomorrow evening.

I will talk to the Abenteuerhallen to make sure that you can put the BBQ stuff in the fridges tonight.

Also,  I was told that they don't really have any Grillzangen.  Who could bring some for Saturday?

**Comment by schorsch** [comment]
i'll bring professional toolz :-)
