### ISSUE TITLE
Rooms/areas

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2014#50]
We should have the followings rooms/areas:
- Main stage
- Lounge/Bar (drinks, coffee, fingerfood, chillout)
- Outside area (tent, beer garden)
- Main room upstairs (for up to 30-40 ppl)
- Small room upstairs (for 10-20 ppl)
- Siebdruck room upstairs
- Skate hall (from 22:00 until 12:00, for sleeping)

Feedback from last year was that the Main stage and the Lounge were a little too close to each other.  Maybe we can find a better solution for this this year.

**Comment by moonglum** [comment]
Shall I add those rooms to the planning tool?

**Comment by jhilden** [comment]
@moonglum make it so

**Comment by moonglum** [comment]
I added the rooms to the tool:

![Rooms](https://cloud.githubusercontent.com/assets/95788/4393684/2724c2d0-441a-11e4-8d24-624713328030.png)

Anything missing?
