### ISSUE TITLE
Shared transportation

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2014#51]
This issue is for people to find shared transportation to the camp.

For example @nerdbabe started a very nice initiative to share a train connection from Berlin https://github.com/NerdBabe/RailsCampTrain/issues/1
I would say the same could be possible for participants coming from the Hamburg area (@colszowka ? @erotte ?) or from the south of Germany.

**Comment by erotte** [comment]
Nice, great idea! I just started an issue: https://github.com/railscamp/railscamp-germany-2014/issues/53
