### ISSUE TITLE
Hamburg area RailsCampTrain 

### ISSUE THREAD

**Issue by erotte** [railscamp/railscamp-germany-2014#53]
Whoohoo,
I'm looking forward to another awesome RailsCamp weekend in cologne. And traveling by train with some peeps from the greater Bremen area (Hamburg, e.g.) would be really great!

So let's do do some planning on that.

Traveling time is around 4h from Hamburg. I would prefer connections without train changes.

So, what's your preferred traveling time? Currently I'm not sure, maybe somewhen in the later friday  afternoon might be a good arrival time.

http://reiseauskunft.bahn.de/bin/query2.exe/dn?ld=9642&seqnr=4&ident=i4.02386742.1407872608&rt=1&rememberSortType=minDeparture&REQ0HafasScrollDir=1

**Comment by colszowka** [comment]
Later friday afternoon sounds good to me :)

**Comment by walski** [comment]
Ola compañeros! So how does departing Hamburg at 15:46h, departing Bremen 16:44h and arriving in Cologne 19:46 sound? ICE no changes.

For the return trip their is either a 15:38h IC which would be in Bremen at 19:14h and in Hamburg at 20:06h. Or we take an ICE a tid bit later at 16:10h from Cologne that is in Bremen at 19:17h and in Hamburg at 20:12h.

Tickets are 124€ or 138€ in 2nd Class and an amazing 138€ or 158€ in first class. As a "Travel Otto aller erster Güte" I would go for that ICE 1st class ticket which is not significantly more expensive but comes with some nice comfort and beer served at your seat ;) But I totally go for whatever it is that suites everyone best.

Let's do it! :train: :dash: :boom: :sparkles:

**Comment by walski** [comment]
By the way: @nesQuick, are you joining us? http://2014.railscamp.de/

**Comment by OleMchls** [comment]
@walski sounds great! I'm in :100: Also 1st class :train2:  of course :sparkles:

**Comment by colszowka** [comment]
We could also get a group ticket - needs at least 6 people, but has highly reduced pricing

**Comment by OleMchls** [comment]
yay, bring it on! What about @Partyschaum @bastiank ?

**Comment by walski** [comment]
Yip and @dennisreimann :)

@colszowka group shit is always fun including "no, those tickets can't be issued digitally but we will mail them to you" :) Shall I get an offer for 6 folks assuming we will be at least 6?

**Comment by colszowka** [comment]
@walski sounds good :)

While we're at it, what about @phoet and @rubiii ?

**Comment by dennisreimann** [comment]
Unfortunately I won't make it to RailsCamp this year. Have fun and enjoy the ride!

**Comment by phoet** [comment]
@colszowka probably not. maybe spontaneously, have fun guys :fireworks:

**Comment by walski** [comment]
Als Gruppenpreis kostet die ICE Verbindung (15:46 hin, 16:10 zurück) in der 2. Klasse: 103€ und in der 1. Klasse 121€ pro Person. Ich habe jetzt komplett von Hamburg aus geschaut, da Bremen aber auch ohne Gruppe nur 104€ pro Person kostet weiß ich nicht genau wie hilfreich das jetzt ist.

**Comment by colszowka** [comment]
+1 in der ersten Klasse dann :)

**Comment by OleMchls** [comment]
**TERMINKONFLIKT:** Ich bin am 26.9 noch auf den [Ruby Days 2014](http://www.rubyday.it/) würde dann aber dann abends am 26. noch nach Köln kommen. D.h. ich bin raus für die Bahnfahrt hin. Aber zurück würd' ich gern :sparkles:1st Class :train2::sparkles:

**Comment by erotte** [comment]
Bahnpreise sind ja im Prinzip schon Gruppenpreise, deshalb lohnen sich die Gruppentarife i.d.R. nicht.
Es wird wschl. sehr viel günstiger, wenn man einzeln Sparpreise bucht, gibts ab 62,50 hin und zurück.

Ich habe eine Bahncard 50 2. Klasse und möchte die auch nutzen, weil's viel billiger ist und weil ich flexibler bin. Der Termin für die Rückfahrt ist mir zu spät, letztes Jahr lief am Sonntag nicht mehr viel.

Mir würde es reichen, wenn wir uns auf einen Zug einigen. 
Beim Gruppenticket bin ich draussen, auch weil ich ggf. früher zurück fahren möchte. 1. Klasse ist kein Problem, das bekomme ich mit einem Bonuspunkte-Upgrade hin.

**Comment by walski** [comment]
Gut klingt also nach:
1. Wir buchen das einzeln
2. Wir nehmen den ICE 15:46h ab HH am Freitag gern 1. Klasse
3. Mag @erotte oder einer der anderen Veteranen nochmal einen Vorschlag machen welcher Zug am Sonntag cool wäre

Danke! <3

**Comment by jhilden** [comment]
> Der Termin für die Rückfahrt ist mir zu spät, letztes Jahr lief am Sonntag nicht mehr viel.

Dann lass uns doch dieses Jahr alle zusammen guckn, dass wir noch ein paar coole Sessions machen am Sonntag.  Das wäre cool.  Ich denke es ist im Prinzip alles nötige da, damit das passieren kann. <3

**Comment by erotte** [comment]
Ich werde am Sonntag wahrscheinlich mittags oder am frühen nachmittag fahren, 13:10 oder 14:10. Ich möchte aber niemals nie, nie, nie Menschen davon abhalten, an coolen Sessions teilzunehmen oder welche zu starten!  Also, plant und bucht die Rückfahrt gern ohne mich, ich komme ggf. spontan dazu.

**Comment by walski** [comment]
Sodele, @nesQuick und ich sind versorgt. 15:46h fahre ich am Freitag (wie besprochen) hin und mit Ole dann am Sonntag um 16:10h zurück. Bahaaam. :boom:

**Comment by OleMchls** [comment]
Was @walski sagt, plus ich komme am Freitag etwas später dazu. Ich lande um `22:40` in CGN, also schön langsam am Freitag, nicht alles wegtrinken :facepunch:

**Comment by walski** [comment]
@colszowka und co, seid ihr jetzt alle an Board und habt tickets?

**Comment by colszowka** [comment]
Confirmed: 15:46 hin, 16:10 zurück, 1. Klasse. Steige schon in Altona ein und dann auch wieder aus :)

**Comment by walski** [comment]
Ein Traum! :+1:

**Comment by erotte** [comment]
Hallo Leute,
Ich sitze gerade spintan beim Kieferchirurgen, gleich gehts los und

**Comment by erotte** [comment]
Alles

**Comment by erotte** [comment]
Das Ding hier lässt sich via mobiles Endgerät nicht so gut bedienen ;-)
Ich bin jedenfalls raus und wünsche euch ein tolles Wochenende!

**Comment by walski** [comment]
Stehst du schon unter Drogen? :( Klingt scheiße, und ich vermute mal das war eine Absage. Lass es dir schnell wieder besser gehen! :ambulance: :sos:

**Comment by RmMsr** [comment]
Beste Besserungz!
