### ISSUE TITLE
Rechnungen an Sponsoren

### ISSUE THREAD

**Issue by koos** [railscamp/railscamp-germany-2014#56]
Hi,
speziell @thilo 
Die Rechnung ist nicht sonderlich 'nett' formuliert (bzw. halt gar nicht formuliert). Ein Dankeschön im Anschreiben, in der Rechnung, etc. wäre super. Nur so als Feedback vom Sponsor.
![screenshot 2014-08-13 15 37 04](https://cloud.githubusercontent.com/assets/8343/3906083/9bbcb8ba-22ef-11e4-95b2-57dd8b7140ca.png)

**Comment by raucao** [comment]
Der E-Mail-Text dazu war ziemlich nett. :)

**Comment by thilo** [comment]
@koos, da hast du recht :( Ich hab mal den Standard Text angepasst das selbst wenn man vergisst etwas zu schreiben die EMail freundlicher ist.  (Sorry vorhin vom falschen account gepostet,)

**Comment by Uepsilon** [comment]
mir fällt gerade auf, dass ihr auf die Beträge noch mal VAT drauf haut. ist das nicht ziemlich doof den Sponsoren gegenüber, wenn man denen die Preise 250€, 500€, 1200€ nennt und dann auf einmal noch 20% Märchensteuer zu kommen?

**Comment by jhilden** [comment]
actually, that's totally normal in the B2B world.  and no sponsor has complained so far.

however, for completeness, we should definitely add a note to the prices we are telling sponsors. @RmMsr

**Comment by raucao** [comment]
Uhm, I have complained twice and not heard back after the last email!

It's completely unnecessary to add that money when sponsors are seated in another EU country and both parties have a VAT ID. Please send us a new invoice with no VAT added.

Thanks!

**Comment by RmMsr** [comment]
@skddc Updated invoice is out. Sorry for the long delay. I was very busy.

@koos Yes, I send the first two invoices without typing a nice message. Later on  I used a template for that. Wasn't meant to be unthankful by any means.

@jhilden Good point. I will communicate that our packages are plus VAT.

**Comment by raucao** [comment]
In order to leave out the VAT, you need to put our VAT ID on the invoice, too. ;)

**Comment by RmMsr** [comment]
I see. That use case does not seem to be supported. I added it inside the Subject as text. Please see if that is sufficient.

**Comment by Uepsilon** [comment]
Since @skddc says it's unnecessary to do so, we'd stick without vat, shouldn't we? Or at least commit to one way.

**Comment by jhilden** [comment]
@Uepsilon that's only for foreign companies with a VAT ID.  For German companies we have to charge VAT

**Comment by Uepsilon** [comment]
ah.. fair enough

**Comment by RmMsr** [comment]
I guess this is solved.
