### ISSUE TITLE
On-site Session Scheduling and Moderation

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2014#58]
We have the online session tool at https://openspacer.org/13-railscamp-germany-2014/ which works really nice so far, but how is it going to happen on-site?  Who wants to take care of this?

@moonglum ? @koos ? @Mobbit ?

@thegcat you said at one point you might be able to do moderation during the event?

**Comment by moonglum** [comment]
I can't promise to be at the camp (I'll probably be in panic mode getting the last stuff of my thesis done), so I can't take over this task.

**Comment by thegcat** [comment]
Same here, I have 2 concerts that WE and planned on attending when not singing, car troubles means I'm not even sure I'll manage that, sorry :crying_cat_face:

**Comment by jhilden** [comment]
We still need somebody here.  What about @skddc ?  Any other suggestions?

@koos did you ask your moderator friend Felix?

**Comment by jhilden** [comment]
This task still has no takers :(   Come on Ruby Community, you can do better than this.

I personally think @colszowka and @skddc would make an awesome moderation duo. 

Or @bumi ?

**Comment by koos** [comment]
Optional Felix can be an MC.
I can do it too if you want… maybe not two days, but one.
 

-----Original Message-----

**Comment by colszowka** [comment]
Haha, yes, I guess this could be fun.

**Comment by m20io** [comment]
I can also cover a day and help preparing - and have fun :)

**Comment by m20io** [comment]
@koos @colszowka Should we do a short call next week to plan a little?

**Comment by RmMsr** [comment]
**Note from one speaker**. The Talk [**Org Hacking for Fun and Profit**](https://openspacer.org/13-railscamp-germany-2014/session/133-org-hacking-for-fun-and-profit/) can be given **only on ~~sunday~~**, because the speaker is not available on day 1 and 2. Please take that in consideration.

**Update: Speaker wants to do the talk on Saturday**

**Comment by m20io** [comment]
@RmMsr thx for the heads up!

**Comment by m20io** [comment]
@koos @colszowka How are you guys doing? Short call tomorrow evening?

**Comment by colszowka** [comment]
Call yes, but tomorrow eve I'm in the stadium. Gotta leave around 4, and might have had beer when back. Wednesday maybe? Or tomorrow noon?

**Comment by m20io** [comment]
@colszowka @koos How about doing the call then tomorrow during the day and 14 oclock? 

The following things are open:
- [ ] session format (how long, breaks)
- [ ] preparation from open spacer
- [ ] orga day 1 (planing session, shift one, shift two)
- [ ] orga day 2 (planing session, shift one, shift two)

**Comment by koos** [comment]
works for me

—
Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by colszowka** [comment]
Yay, lets do that then. I'm thedeadserious on Skype and myself on g+. See you tomorrow!

**Comment by colszowka** [comment]
Tadaa, I forgot I have my dad visiting at 2... A bit earlier? Today evening around 6? Sorry for the hassle :/

**Comment by koos** [comment]
so for my it works only NOW then 

—
Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by m20io** [comment]
We are great - I just missed the time :) Lets try again tomorrow and do it over skype - im martin2punkt0 there.

How about 2 o clock again? (im flexible - almost hole day)

**Comment by koos** [comment]
i’ll try at 2pm

—
Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by colszowka** [comment]
Works for me, see you later gents :)

**Comment by m20io** [comment]
Great. What about you @koos

**Comment by koos** [comment]
i’ll try, but cannot promise. but 4pm would be perfect for me.

—
Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by RmMsr** [comment]
Update to my note above regarding the Session 'Org Hacking for Fun and Profit'. The speaker changed his plans and wants to do the talk on Saturday.

**Comment by m20io** [comment]
![img_20140927_114756](https://cloud.githubusercontent.com/assets/701754/4430365/849d17f6-462b-11e4-8e8d-b6ee18ba232a.jpg)

**Comment by m20io** [comment]
![1411811393542](https://cloud.githubusercontent.com/assets/701754/4430369/accb41e4-462b-11e4-9d32-bfd997c38757.jpg)
Small room 13 und 14

**Comment by koos** [comment]
@m20io wo soll ich die arduino und security session einplanen? welcher track? ansonsten: http://lanyrd.com/2014/rcg14/
