### ISSUE TITLE
Usergroup Marketing

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2014#59]
Here are some upcoming dates of Ruby Usergroups.  Let's try to reach those groups at the right time and make sure they know about the Railscamp.
- 3.9. (maybe) http://bremen.onruby.de/
- 4.9. http://dresden.onruby.de/events/vortrag-domain-focused-rails
- 4.9. http://berlin.onruby.de/
- 10.9. http://hamburg.onruby.de/events/ruby-usergroup-hamburg-september-2014

Any other dates you know?

**Comment by jhilden** [comment]
bump.  any takers for this job?

**Comment by marcel12bell** [comment]
Ok, I'm on it.

**Comment by endverbraucher** [comment]
I already talked to a dresden ruby user group member about this. I will remember him :)

**Comment by marcel12bell** [comment]
to late... ;-)

**Comment by endverbraucher** [comment]
„doppelt hält besser“ ;-)

**Comment by pbrueske** [comment]
Habe es mal in die Monster on Rails Gruppe aus Münster gepostet, nächstes Treffen ist aber leider erst am 25.09. ;(
