### ISSUE TITLE
pictures from 2013

### ISSUE THREAD

**Issue by endverbraucher** [railscamp/railscamp-germany-2014#6]

**Comment by erdnusskeks** [comment]
We want to put photos on the website. Do you have any from last year's event we could use? Thanks!

**Comment by jhilden** [comment]
Here are a couple I found:
- https://secure.flickr.com/photos/noddleholz/sets/72157634866045576  by @unimatrixZxero
- http://abstraction.killedthecat.net/railscamp-germany-2013-rcg13/  by @rin
- http://www.allanlavell.com/  by @thinkrad
- https://www.flickr.com/photos/p886/9377813359  by @p886 

It would be great if the authors of the photos could give us permission here.  But if we do propper atribution, I think it should be OK in any case.

**Comment by erdnusskeks** [comment]
I also found these: http://eventifier.com/event/rcg13/photos

**Comment by p886** [comment]
Here's my complete railscamp 2013 album:
https://www.flickr.com/photos/p886/sets/72157634815067879/

You have my permission to do whatever you want with these pictures if you
attribute me. I licensed these as CC-BY so you're good to go :)

On Thu, May 8, 2014 at 10:47 PM, Denise notifications@github.com wrote:

> I also found these: http://eventifier.com/event/rcg13/photos
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/railscamp/railscamp-germany-2014/issues/6#issuecomment-42604211
> .

## 

Philipp Antar

**Comment by erdnusskeks** [comment]
Cool, thanks, Philipp!

**Comment by unimatrixZxero** [comment]
You can use mine. (As posted above: https://www.flickr.com/photos/noddleholz/sets/72157634866045576/)

**Comment by erdnusskeks** [comment]
Thanks, @unimatrixZxero! : )

**Comment by erdnusskeks** [comment]
On the website from 2013, you can find the link to the IRC channel:
irc://irc.freenode.net:7000/railcamp_de (go to http://2013.railscamp.de/contribute/) 
Is this still working? Or is there anything that needs to be updated?
Or should we just comment it out for the moment and wait for further instructions? ; )

One line below, you can find this link to a orga mailing list:
https://groups.google.com/forum/#!forum/railscamp2013
It was used as a non-public channel. That’s good! Let’s keep this but don’t publish it anymore - as we have already a new mailing list for organizing: https://groups.google.com/forum/#!forum/railscamp-de

**Comment by raucao** [comment]
Of course IRC is working. Just join the channel. ;)

Why a new mailing list?

**Comment by erdnusskeks** [comment]
The new one is for everyone who wants to join and to help. 

As written on last year's website: 
"The orga mailing list is the only non-public channel, which we only use for confidential information. If you want access, just request it. It’s not necessary for anything other than looking at a few boring numbers, though. ;)"
We already talked about a mailing list for confidential information. There it is! Actually, this is no "orga" mailing list but a mailing list for internal matter (numbers and so on).

**Comment by raucao** [comment]
Yer, so why a new one? Am I missing sth?

**Comment by erdnusskeks** [comment]
Ok, maybe we don't need the new mailing list, at all. 
It seems there are just Jakob and me who are using the new list. ; )

In my understanding, there's supposed to be one for confidential issues, and one for general issues. As for me, I don't need to know any numbers, but I'd like to share information. Otherwise, for sharing information I don't necessary need a mailing list. Because we have the GitHub issues.

Or was there any other reason for starting the new mailing list? @jhilden? I don't remember... 
Sorry if I confused everyone. At last, I'm confused, too.

**Comment by endverbraucher** [comment]
I also think we don’t need a second mailing list. One for confidential stuff should be enough. For all other conversations, discussions and information sharing Github Issues should be the place to be. That worked very well last year.

**Comment by jhilden** [comment]
@slogmen can you take ownership of the website publishing process and explain it to the people that need to know?   We need to decide (and document), if we stick to the `git subtree` process that we used last year or if we maybe do something else (e.g. http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html)

**Comment by endverbraucher** [comment]
Yes. I will have a look at this at the weekend. I will document the preferred way to do this. Thanks for the link!

**Comment by endverbraucher** [comment]
Done. I’ve added a rakefile with a task for publishing the page. All you need to do is run `rake site:publish` after you committed your changes to the master branch. Additionally the readme is updated with deployment instructions.

**Comment by endverbraucher** [comment]
We’re already online with a light version of the site. The site contains infos about the venue and how to contribute. That’s all.

**Comment by cice** [comment]
i have a bunch of pictures from 2013, i can put them on dropbox later.

**Comment by endverbraucher** [comment]
@cice it would be great if you put your pictures somewhere.

to all: Thank you very much for contributing your photos. In the next days I will build a nice little gallery for the railscamp site. Hopefully all your pictures help us to convince some more people to join our nice little camp. :)

**Comment by jhilden** [comment]
@slogmen what's the status here?  Something super simple with only 6 pics would already be awesome.  We can always build something better later.

**Comment by erdnusskeks** [comment]
Some pictures are online, now.
http://2014.railscamp.de/news/2014/07/18/gallery.html

**Comment by RmMsr** [comment]
@unimatrixZxero You have some great images in that collection. Is there a sane way to get the images files for RailsCamp brochures or presentations? Flickr tells me that the owner does not want the images to be downloaded.

**Comment by cice** [comment]
i have a small set of pictures on flickr: https://www.flickr.com/photos/cice-wise/sets/72157634815856883/

**Comment by unimatrixZxero** [comment]
@RmMsr Try these on for size: https://copy.com/NW6HStB4lgVEyuqD

**Comment by jhilden** [comment]
Closing this for now

**Comment by jhilden** [comment]
Is there a chance that we can put a small gallery on the website (with a link in the main nav)?  Who could do that?  @slogmen ?

**Comment by endverbraucher** [comment]
Okay I’m on this.

**Comment by aelavell** [comment]
totally chill with whatever you want

**Comment by jhilden** [comment]
@slogmen any progress here?

**Comment by RmMsr** [comment]
I guess 2013 pictures are no longer relevant. Closing ...
