### ISSUE TITLE
University Marketing

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2014#60]
Send emails to relevant university deparment mailing lists in the area.

Who can send an email to FH Sankt Augustin?  @DonSchado

Who can send an email to FH Köln Informatik?  @koos @tmschndr @stephanpavlovic

Most of the required information is in this blogpost:  http://2014.railscamp.de/news/2014/05/30/join-us-for-another-epic-railscamp-germany.html

**Comment by badboy** [comment]
I'll see who I can contact at RWTH Aachen

Update: I posted in two Facebook groups for now.
