### ISSUE TITLE
Better communication: What is it?

### ISSUE THREAD

**Issue by badboy** [railscamp/railscamp-germany-2014#61]
I posted the link in my university's facebook group today and two people complained they didn't really get what RailsCamp is about.

I think a short explanation on the main site would help. Something along the lines of [the blog post](http://2014.railscamp.de/news/2014/05/30/join-us-for-another-epic-railscamp-germany.html), but also mentioning that it's about Rails (but not limited to topics around Rails, also Ruby). I'm not good at formulating this, but it will definitely help to get info about this event to total beginners.

**Comment by jhilden** [comment]
Thanks for the feedback.  We can certainly find somebody for the formulating, but it would be good to know what content would need to be in the text, e.g. what questions it would need to answer.

**Comment by badboy** [comment]
> Nachdem ich die Seite durchgelesen habe, hab ich immer noch nicht verstanden, worum es geht. Ruby on Rails?
> Würde auch gerne wissen, worum es genau geht Werde aus der Seite auch nicht schlau. Laut Google geht es aber um Rails, ja.
- What is it? → A (Un)conference with talks and workshops, but also some fun events
- What is it about? → Rails, the open-source web framework in Ruby
- Who is invited? → Everyone that works with Rails or Ruby or is just getting started with Ruby

**Comment by jhilden** [comment]
I added a quick facts box to the homepage:  http://2014.railscamp.de/   Feedback, corrections and improvements are welcome.

**Comment by jhilden** [comment]
Closing this, since I got no feedback.
