### ISSUE TITLE
Workshop for Codecademy Finalists?

### ISSUE THREAD

**Issue by tr37ion** [railscamp/railscamp-germany-2014#62]
I'm new to Ruby eg Rails, therefore I would like to get in contact with experienced people who could help with taking the steep learning curve of Ruby/Rails.

I didn't read many of already posted issues, yet I have an idea of offering two "Ruby/Rails Beginner Workshops" at the summit. The idea is, that everyone who wants to participate in those workshops is suggested to finish the following Codecademy courses:
- Ruby - http://www.codecademy.com/en/tracks/ruby
- HTML & CSS - http://www.codecademy.com/en/tracks/web

This would give the learner the chance to find specific topics which are difficult to understand and also raises the workshop level to an all in all almost same student's knowledge level. 

Therefore, the teachers ...
- know exactly which knowledge level is present
- which topics every student took
- can prepare himself to a certain level of knowledge
- and can develop an even better "on the job" development example to teach further things.

On the other side, the students ...
- are initially motivated to finalize the basic concepts of Ruby
- they are giving a hand by Codecademy students
- they gain more confidence by participating in the course
- they see exactly see with which topics they have further questions
- the entire class starts with almost the same level.
- they could group together before they see each other in the workshop
- are well motivated to participate in this workshop
- and they will gain even more confidence in asking questions

Benefits:
- The workshop will be the right place to ask all unclear topics
- It may be more interesting for each student, because everyone can ask the really important issues
- Students help each other while also have their own questions
- No one has to be shy to ask questions on the Codecademy course's topics
- The open topics are explained by experienced teachers in class.
- It's easier to ask questions for students
- The students learn from difficulties they or others had

OMG, I wrote so much. To sum it up, I think you get the idea. Now it's on you to say what do you think of that spontaneous idea :)

**Comment by jhilden** [comment]
Sounds like a neat idea.  Could you post your session proposal here https://openspacer.org/13-railscamp-germany-2014/ so we can find out how many people would be interested in participating in such a session?

**Comment by RmMsr** [comment]
@tr37ion I find that an great idea. Do you have an opportunity to announce this inside code academy? Besides that do you have an idea to contact other interested people about the course and the RailsCamp as meeting place? Just make some noise and keep us updated. I am confident we could find someone willing to coach.

**Comment by maxruby** [comment]
This is a great idea to get started.  In addition, it would be great to have a session to discuss opportunities for contributing to the Ruby/Rails community in areas that remain underdeveloped such as image processing, computer vision applications.  I would very much like to take advantage of my background and interest in imaging/tracking using MATLAB to improve Rails Web applications so it would be nice to get advice from those with experience in Web development.

**Comment by RmMsr** [comment]
@tr37ion Just want to ping you. Did you have the chance to contact some students? Is it possible to help?
