### ISSUE TITLE
Presentation-Slides optimization

### ISSUE THREAD

**Issue by Uepsilon** [railscamp/railscamp-germany-2014#63]
I guess we should advise all potential speakers to keep their slides in black on white style, especially for code snipets. 

I found it rather difficult to read some slides in the room at the froscon. I guess, even with a good projector, it will be even harder to read at the venue. 

@erdnusskeks maybe you can tweet about it or even add a blog entry? or whoever is in charge.

**Comment by erdnusskeks** [comment]
I will tweet it.

**Comment by Uepsilon** [comment]
You just did.. Awesome!
