### ISSUE TITLE
CoderDojo @ Railscamp

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2014#64]
The people behind the Coderdojo Cologne (https://www.facebook.com/coderdojocgn),  are planning to have session during the Camp.  The objective is to teach "coding" to children (of roughly ages 7-14).

Let's collect all information about the dojo here.

**Date:**   Since the the Coderdojo events have been on Saturdays in the past, I would think it will take place on the Saturday of the camp the 27.9.

**Location:** If the small room upstairs is enough I think we should block that room for Saturday.  If more space is needed we need to figure out something else.

**Coaches**:  @marcel12bell @moonglum @erdnusskeks @bascht @seanlilmateus @koos ...

Here is a link to their last event:  https://zen.coderdojo.com/dojo/385

**Comment by jhilden** [comment]
Would be great if you could also add the Coderdojo Session to the session planning tool:  https://openspacer.org/13-railscamp-germany-2014/session/

**Comment by bascht** [comment]
Sounds great. We waited for an official »Go« from the Railscamp orga team, so if it's okay for us to organize a Dojo during Railscamp, I'd be more than happy to announce it & create a session for it. :)

**Comment by jhilden** [comment]
"Go, go, go" :)    The Railscamp Orga Team is really excited to have you on board :)

**Comment by bascht** [comment]
:dancers: 

Regarding
- Date
  Yep. It'd be on a saturday & we start at 11 / 12am and the dojo will be ~ 4 hours with a short break.
- Location
  The room would be great. As we're timeboxing it, you don't have to block it for the whole day.

**Comment by jhilden** [comment]
It would be good if you could provide a "guest list" for the recpection, of the kids and parents who are planning to come. That way we can make sure that they get in for free, if they only want to attend the dojo.

I guess it would be good if we had some sort of special badge for them #65

**Comment by bascht** [comment]
Sure. We'll bring a list with us. The registration for the CoderDojo is done via zen.coderdojo.com – and I suppose @koos has an account over there.
