### ISSUE TITLE
Badges & Reception

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2014#65]
We decided that we will have simpler badges than last year.  Just the red-white striped tape from last year and the particapant name on it.

@erdnusskeks will order the supplies
- tape
- pens to write
- klebepunkte (to vote for sessions, ~10-20 p.p.)

We will also need people to man the reception area, hand out badges, take in cash, ...

**Comment by erdnusskeks** [comment]
I would order this tape:
http://www.amazon.de/gp/product/B003A6HTIM/ref=ox_sc_act_title_2?ie=UTF8&psc=1&smid=A3JWKAKR8XB7XF
tesa 58131-00000-00 Signal Premium Markierungs- und Warnklebeband 66 m : 50 mm, rot/weiß
9,45 €

and these Klebepunkte:
http://www.amazon.de/Herma-2212-Vielzwecketiketten-Papier-St%C3%BCck/dp/B000M247Q4/ref=sr_1_10?s=officeproduct&ie=UTF8&qid=1409143517&sr=1-10&keywords=klebepunkte
Herma 2212 Vielzwecketiketten Ø 8 mm, rund Papier matt 5632 Stück, rot
6,92 €

via Amazon.

Does anyone get discount on those products? Let me know! Thanks! : )

I also found these address stickers:
http://www.amazon.de/Herma-8634-Adressetiketten-Premium-Papier/dp/B000M249G2/ref=sr_1_5?s=officeproduct&ie=UTF8&qid=1409307119&sr=1-5&keywords=etiketten
Herma 8634 Adressetiketten Premium A4 70 x 42,3 mm Papier matt 210 Stück, weiß
6,98 €

We could prepare the stickers by printing out the names of all ticket buyers and, at least, don't have to write their names on the tape. We just need to stick the stickers on the pretty tape. : )
For everyone else (who buys a ticket directly at the venue) we will still have the "edding on tape" option. ; )

I guess we don't need to buy (black) eddings, do we?
Last year, someone brought pens and scissors to the camp - I think it was @tatjanala, right? 

I would help at the reception area but maybe not the whole time.
What about you, @p886? Do you like to help? We were a great team last year! : )

**Comment by p886** [comment]
Sure, I would be glad to help out at the reception :)

On Fri, Aug 29, 2014 at 12:29 PM, Denise notifications@github.com wrote:

> I would order this tape:
> 
> http://www.amazon.de/gp/product/B003A6HTIM/ref=ox_sc_act_title_2?ie=UTF8&psc=1&smid=A3JWKAKR8XB7XF
> tesa 58131-00000-00 Signal Premium Markierungs- und Warnklebeband 66 m :
> 50 mm, rot/weiß
> 9,45 EURO
> 
> and these Klebepunkte:
> 
> http://www.amazon.de/Herma-2212-Vielzwecketiketten-Papier-St%C3%BCck/dp/B000M247Q4/ref=sr_1_10?s=officeproduct&ie=UTF8&qid=1409143517&sr=1-10&keywords=klebepunkte
> Herma 2212 Vielzwecketiketten Ø 8 mm, rund Papier matt 5632 Stück, rot
> 6,92 EURO
> 
> via Amazon.
> 
> Does anyone get discount on those products? Let me know! Thanks! : )
> 
> I also found these address stickers:
> 
> http://www.amazon.de/Herma-8634-Adressetiketten-Premium-Papier/dp/B000M249G2/ref=sr_1_5?s=officeproduct&ie=UTF8&qid=1409307119&sr=1-5&keywords=etiketten
> Herma 8634 Adressetiketten Premium A4 70 x 42,3 mm Papier matt 210 Stück,
> weiß
> 6,98 EURO
> 
> We could prepare the stickers by printing out the names of all ticket
> buyers and, at least, don't have to write their names on the tape. We just
> need to stick the stickers on the pretty tape. : )
> For everyone else (who buys a ticket directly at the venue) we will still
> have the "edding on tape" option. ; )
> 
> I guess we don't need to buy (black) eddings, do we?
> Last year, someone brought pens and scissors to the camp - I think it was
> @tatjanala https://github.com/tatjanala, right?
> 
> I would help at the reception area but maybe not the whole time.
> What about you, @p886 https://github.com/p886? Do you like to help? We
> were a great team last year! : )
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/railscamp/railscamp-germany-2014/issues/65#issuecomment-53860267
> .

## 

Philipp Antar

**Comment by jhilden** [comment]
Tape and Klebepunkte sound good.  Please go ahead and order them.

I could bring some Etikettenpapier.  We would need to cut it ourselfes, but I think it would also work.

**Comment by erdnusskeks** [comment]
I will also bring some black/yellow tape for special badges (as Jakob mentioned in issue #64). We can use it for the CoderDojo kids and their parents and also for the participants of the (special) felt ruby session. If someone wants to stay longer we ask for some contribution (money, of course! ; ) and change the name tape to red/white.

**Comment by erdnusskeks** [comment]
Tape and Klebepunkte are ordered.
