### ISSUE TITLE
dawanda Lange Nacht des Selbermachens

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2014#66]
Maybe we can use that a little bit for marketing:   http://de.dawanda.com/s/Events/32071-Lange-Nacht-des-Selbermachens

**Comment by jhilden** [comment]
We are in.  Thanks a lot @erdnusskeks 

https://www.eventbrite.de/e/filz-rubies-tickets-12893574027
http://de.dawanda.com/s/Events/32071-Fuer-Teilnehmer#zip5

Please spread it.

**Comment by jhilden** [comment]
Only thing left to do is to enter this session into http://lanyrd.com/2014/rcg14/

**Comment by jhilden** [comment]
lanyrd session is created:  http://lanyrd.com/2014/rcg14/sddmyd/

I guess it makes sense to have this session in the smaller room upstairs.  The Coderdojo goes until 17:00 so that should be fine, if it starts at 18:00.

Closing this ticket, unless there are more general things to organize.  Looking forward to my first sewing experiences.

**Comment by jhilden** [comment]
good news.  https://www.makerist.de will sponsor the supplies for the sewing session.  @erdnusskeks can you remove the "6€ Umkostenbeitrag" from the descriptions?

**Comment by erdnusskeks** [comment]
Done!
