### ISSUE TITLE
Foosball tables

### ISSUE THREAD

**Issue by RmMsr** [railscamp/railscamp-germany-2014#67]
We need 2 Foosball / soccer tables for a sponsor.

Last year we got an offering of 280 EUR without transport from meinkicker.com. See: https://github.com/railscamp/railscamp-germany-2013/issues/21#issuecomment-54308691

**Comment by RmMsr** [comment]
Ok, sponsor deal is closed. Now we need:
- [ ] Check prices and availability
- [ ] Make sure we have transportation to and from the venue
- [ ] Prepare and do branding with sponsor logo

**Comment by RmMsr** [comment]
@railsbros-dirk Could you ask them?

**Comment by jhilden** [comment]
If @railsbros-dirk or somebody else could take care of this, as it would free up some time for the core organizers to take care of other things.

**Comment by jhilden** [comment]
Or maybe @stephanpavlovic ?

**Comment by code-later** [comment]
It would be great if someone else could take care of this since I'm currently quite short on available time :-(

**Comment by stephanpavlovic** [comment]
I'll take care of it.Will contact the guys today/tomorrow

**Comment by koos** [comment]
If we dont have money lets take the one from linie7 our old one

**Comment by jhilden** [comment]
The tables will be sponsored by MailJet.  We just need to take care of the logistics.

**Comment by stephanpavlovic** [comment]
Seems as if the raised the prices a lot. Current offer is 500 Euros for 2 tables 2 days, I already talked to them (first offer was 600). @railsbros-dirk do younknow anybody there in particular? My contact was Frank Dörrie...

**Comment by code-later** [comment]
@stephanpavlovic not really, but @larsvegas has. Maybe he can help.

**Comment by stephanpavlovic** [comment]
150 Euro are transfer, and they are sitting also in Kalk "Dieselstr. 26, 51103 Köln", maybe we can get them by ourselves somehow?

**Comment by larsvegas** [comment]
@stephanpavlovic I only know eliaz. We always ordered including theire logistics. As far as i remember the price was like this before...

**Comment by stephanpavlovic** [comment]
Ok, in https://github.com/railscamp/railscamp-germany-2014/issues/67#issue-41973918 it said last year it was 280 for everything. Nearly half of want is on the table for this year...

**Comment by larsvegas** [comment]
You talked to Eliaz, did you?

Lars

**Comment by stephanpavlovic** [comment]
Me, as mentioned above I talked to Frank, maybe you can talk to Eliaz?

**Comment by larsvegas** [comment]
Hey Stephan, 
call me back please. :)

**Comment by stephanpavlovic** [comment]
So Deal mit meinkicker.de für 400 Euro inkl. Anlieferung ist unter Dach und Fach

**Comment by larsvegas** [comment]
Cool!!! :)

Lars

2014-09-23 11:30 GMT+02:00 Stephan Pavlovic notifications@github.com:

> So Deal mit meinkicker.de für 400 Euro inkl. Anlieferung ist unter Dach
> und Fach
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/railscamp/railscamp-germany-2014/issues/67#issuecomment-56494979
> .

## 

Lars Wolff · lw@synpro.io · +49 177 6009780
SynPro.io  · Simarplatz 6 · 50825 Köln
http://synpro.io

**Comment by Uepsilon** [comment]
@stephanpavlovic wann kommen die denn ca?

**Comment by stephanpavlovic** [comment]
Muss morgen mal da anrufen, eigentlich wollte der Verantwortliche sich heute bei mir melden...
