### ISSUE TITLE
Monday after the camp

### ISSUE THREAD

**Issue by RmMsr** [railscamp/railscamp-germany-2014#68]
Can we leave one larger piece of equipment at the venue for a logistics company to pick it up on monday?

/cc @jhilden

**Comment by jhilden** [comment]
we left some things there last year until Monday and it wasn't an issue.

**Comment by RmMsr** [comment]
Cool. Will there be someone during monday to open the door and tell the carrier where to find the items?

The goods will arrive on friday and be picked up on monday. Shall I forward the http://ahk.abenteuerhallenkalk.de/kontakt/ Information to the transportation company or do we have a direct contact?

**Comment by jhilden** [comment]
Last year the tent and the empty drink crates were picked up on Monday.

We just need to make sure on Sunday that whoever will be present at the Abenteuerhallen (there is always somebody there from at least 10:00) knows who is coming to pick up what and where it can be found.

**Comment by RmMsr** [comment]
Okay. That's fine
