### ISSUE TITLE
Barzahlungen/Spendenquittungen

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2014#69]
@thilo can you explain how exactly we are going to handle when people are paying/donating in cash at the location.  Will you bring the necessary papers/forms?

In addition makerist asked if they could get a Spendenquittung for donating supplies for the sewing session #66

**Comment by thilo** [comment]
donations can be collected in a jar or box, if we sell tickets (you can't attend the camp without paying) we have to write down how many tickets we sold for which price inkl tax. Regarding makerist, they can send us an invoice and an a letter where they are stating that they like to donate the invoiced amount (with ref to invoice and actual amount excl tax) than we can send them a spendenbescheinigung.
