### ISSUE TITLE
Cocktails

### ISSUE THREAD

**Issue by badboy** [railscamp/railscamp-germany-2014#72]
@eimann and I thought about mixing cocktails right at the camp. 
We already have some equipment, delicious beverages and other ingredients.
@jhilden said he could provide a few more things (shaker, ice bucket, …)

We would offer a cocktail for a small price (probably 3-4€), just to cover our own expenses.

What do you think? Are you interested to drink some nice cocktails at Railscamp?

**Comment by eimann** [comment]
@lauralindal said she would like to help :) We have all the equipment (could use some more glasses, highball and lowball). We need a freezer for crushed ice. And we don't have mate for tschunk. I'll get a list ready with drinks we can provide. @badboy and I will take care of appropiate shopping (except of the mate).

**Comment by lauralindal** [comment]
yeah, i'll help. i even know how to do that zuckerrand on the glasses!

**Comment by badboy** [comment]
:+1: for zuckerrand

**Comment by jhilden** [comment]
This is roughly what I have:
- ~50 IKEA Pokal glasses (http://www.ikea.com/de/de/catalog/products/10270478/).  not really any lowball glasses.
- ice bucket + shovel
- 1-2 shakers
- a good ice crusher
- some straws, decoration stuff, bar spoons, ...

I think there was a freezer at the Abenteuerhallen and they should also have some sort of glasses.  I will try to check next time I'm there.

**Comment by Uepsilon** [comment]
@eimann mate will be provided among other softdrinks.. I ordered some extra crates compared to last year's consumption just to be safe so there will be no shortage ;)

**Comment by eimann** [comment]
I can bring:
- 3x four 5cm Ice Ball Molds
- 4x 6cm Ice Ball Molds
- 20x Pourer
- Soda Siphon
- 2x Shaker
- Knifes
- Cocktail Piekser
- some Jiggers
- Barloeffel
- mortar and some mashers
- Eisschaufel
- 2x Myers Rum Original Dark
- 1x Belvedere Vodka
- 1x Idol Vodka
- 1x Pigalle Vodka
- 1x Grey Goose Vodka
- 3x Havana Club 3yo 1l
- 1x Cachaca
- 1x Kahlua
- 1x Martini Blanco
- 2x Southern Comfort
- 1x Ungava Gin
- 10x Hitchcock Lime Juice
- 2x Hitchcock Lemon Juice 1l
- 1x Rose's Lemon Juice 0.7l
- 1x Jaegermeister 1l
- 15x Fentimans Tonic
- 10x Thomas Henry Tonic
- 2x Reynac Pineau
- 1x Gansloser Black Gin
- 1x De Kuyper Triple Sec
- 1x Giffard Blue Curacao
- 1x Galliano Vanilla
- 1x Noilly Prat
- 1x Amate Anejo
- 1-2x Monkey47 Sloe Gin
- 1-2x Monkey47 Dry Gin
- 1x Botucal
- 1x Diplomatico
- 1x Drambuie
- 1x Glenfiddich
- 1x some Tequila stuff ...
- probably more vermouth

Sirups
- Grenadine
- Mango
- Limone
- Cranberry
- Ananas 
  ... and about 10 more

**Comment by eimann** [comment]
Oh, and about 12x Schott Zwiesel Martini glasses, around 12x Arcoroc 0.5l Tschnuk glasses, and some lowball/oldfashioned glasses (six I think), and another 6x highball

**Comment by eimann** [comment]
Nerdy
- Tschunk

Fruity
- Planter's Punch
- Pink Lady
- Bay Breeze
- Tequila Sunrise (and variations of it)

Not so fruity
- White Russian
- Rusty Nail
- Gin Tonic
- Moscow Mule

Maybe we only do a subset of those. We'll check Saturday morning when there's time to plan the amount + what to mix.

**Comment by eimann** [comment]
Working out the recipes
![screen shot 2014-09-27 at 13 37 33](https://cloud.githubusercontent.com/assets/2742432/4430633/b6410556-463a-11e4-97fb-131b463c7d58.png)

**Comment by eimann** [comment]
To buy:
2x Pineapple juice
2x Mango juice
2x Kirschsaft
2x Banana juice
2x Orange juice
14x fresh oranges

enough mint leaves + basil leaves
45x Limes at least
2x Brown sugar 500g
2x White sugar 500g

**Comment by eimann** [comment]
estimated statistics:
Antica Smash 4
Gimlet 1
Basil Smash 1
Mojito 8
Rusty Nail 4
Gin Tonic 8
Gin Fizz 10
Moscow Mule 9
Old Fashioned 4
Tschunk 9
Planter's Punch 8
Pink Lady 3
Bay Breeze 2
Tequila Sunrise 5

No statistics on the amount of liquids :(

**Comment by jhilden** [comment]
It was super tastey!  Thank you sooo much @eimann @badboy and @lauralindal
