### ISSUE TITLE
Setup on Friday

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2014#73]
Who can come early on Friday and help setting things up?
- stage
- beamer setup
- audio system
- partition between parts of the hall
- tent
- reception table area
- job board
- put drinks away
- coffee setup
- ....

5-10 people would be nice.

I will be there from 10:00 on.  Please reply to this issue if you can also come,  at what time and what you could help with.

**Comment by erdnusskeks** [comment]
I will come as early as possible. Afternoon seems to be possible, maybe even earlier. I could take care of the reception table area and anything else except from technical stuff. ; )

**Comment by Uepsilon** [comment]
I'll come around asap, maybe 4ish, maybe earlier

**Comment by jhilden** [comment]
Also, we could use somebody with a car that could transport some stuff for us on Friday (and also after the event).
- pickup @bitboxer with the wifi equipment from the main trainstation at 11:09
- transport things (fatboys, beamer, cables, office stuff, ...) from the railslove office to the venue

Anybody that can help?
