### ISSUE TITLE
Video recording

### ISSUE THREAD

**Issue by RmMsr** [railscamp/railscamp-germany-2014#74]
I would like to have video recording on the main stage.

Selfnotes:
- [ ] Audio via XLR from Stage
- [ ] Screengraber for slides
- [ ] Good camera
- [ ] Insurance for camera
- [ ] Timecode / cutting solution

**Comment by jhilden** [comment]
Closing this for now, since it's only a couple days until the event and didn't hear anything.  Please reopen as necessary
