### ISSUE TITLE
Social Wall + Gallery

### ISSUE THREAD

**Issue by moonglum** [railscamp/railscamp-germany-2014#79]
Hey :smile: 

The guys from open spacer asked if we have an official hashtag and if we want to use it to activate the social wall and gallery feature. What do you think? :smile: 

Examples:
- [Wall](https://openspacer.org/1-open-summit-2014/wall)
- [Gallery](https://openspacer.org/1-open-summit-2014/gallery)

**Comment by jhilden** [comment]
Sure, why not.  Our official hashtag is **#rcg14**

**Comment by moonglum** [comment]
Wir haben jetzt eine [Social Wall](https://openspacer.org/13-railscamp-germany-2014/wall/).

**Comment by jhilden** [comment]
cool stuff.  thanks.  maybe you could forward a feature request to them, that they should consider deduplicating retweeted messages.
