### ISSUE TITLE
list of possible sponsors

### ISSUE THREAD

**Issue by m20io** [railscamp/railscamp-germany-2014#8]
http://titanpad.com/BSc5bPt5S3

**Comment by erdnusskeks** [comment]
These links aren't active any more: 
Example 1: Sponsorsheet we're using at Interactive Cologne: https://www.dropbox.com/s/pi7cvmk3lm718hx/sponsorpack_new.pdf

Example 2: Sponsorsheet we used last year for the Euruko: https://www.dropbox.com/s/c8g5c4ux7k5843c/big_bang_euruko_sponsor_package.pdf

Does anyone have access to the files and can publish them (maybe in the google group)?
Perhaps there is also a sheet for this year's Interactive Cologne sponsors available?

**Comment by jhilden** [comment]
Those examples were provided by @koos, he should be able to help you out.

**Comment by m20io** [comment]
super - dann kümmere ich mich weiter darum.

**Comment by jhilden** [comment]
we have a first version of the sponsors page:  http://2014.railscamp.de/sponsors/

@erdnusskeks can you announce the sponsors on twitter?

**Comment by erdnusskeks** [comment]
Done!

2014-06-18 21:19 GMT+02:00 Jakob Hilden notifications@github.com:

**Comment by RmMsr** [comment]
Great! Is Could you please also update the Checklist in the spreadsheet whenever we mentioned the Sponsor in Social Media or added them to the website (last columns)?

https://docs.google.com/spreadsheets/d/10N-HksIwP9vZE2GBcJWEl4To_cXOO42-GRy08V4bVqI/edit#gid=0

**Comment by erdnusskeks** [comment]
Sheet is up-to-date.

I also added Putpat as a potential sponsor. Last year we enjoyed their
Freibier. ; )

2014-06-24 17:36 GMT+02:00 RmMsr notifications@github.com:

**Comment by m20io** [comment]
@koos Could send @RmMsr or me the List of companies you mentioned in the conf call?

**Comment by thegcat** [comment]
@planio was interested in sponsoring too and it seems there was a first contact, @yeah never really heard back though. Could you contact him again? Furthermore: how many attendees are you planning on?

**Comment by RmMsr** [comment]
@thegcat I haven't heard anything lately. AFAIK they wanted the brochure. @m20io Do you know more? I'd be glad to provide them with info. I guess @yeah is the correct contact?

**Comment by thegcat** [comment]
Either @yeah or directly support@plan.io :-)

**Comment by RmMsr** [comment]
@thegcat Thanks. They shall hear from us within two days ;-)

There is this spreadsheet with sponsors including addresses (hopefully) from last year. I do not know who owns it. I'd like to use the data again. Can someone access it?

https://docs.google.com/spreadsheet/ccc?key=0ArguUUbzyB64dEdnZVV2VjhvUG1mQ1Uyc09xd3gwaFE#gid=0

**Comment by jhilden** [comment]
@RmMsr access granted

**Comment by RmMsr** [comment]
Whoop. That was fast. Thanks. :)

**Comment by m20io** [comment]
@RmMsr @thegcat plan.io is interessted on becoming a salior again - I send them the presentation and will talk to them again.

**Comment by erdnusskeks** [comment]
Have another look at the titanpad: https://titanpad.com/BSc5bPt5S3 - there are some more potential sponsors to ask for money, coffee and more. ; )

**Comment by RmMsr** [comment]
Link is also inside the Google spreadsheet
