### ISSUE TITLE
Radiointercom

### ISSUE THREAD

**Issue by eimann** [railscamp/railscamp-germany-2014#80]
We will bring a radiointercom system with a repeater (will be placed by us at Abenteuerhallen around 1000/1015 on Friday morning). We need the radiointercom for easier setup of the Internet uplink.
If you need a radio during turnup/the event please contact me. We have 2-3 radios left. If we need more, please contact me so I can arrange some more.
Coverage will be around 1-2km around the Abenteuerhallen. We will only have one callgroup and no data/short-message services. So only voice calls to the group are supported.

**Comment by jhilden** [comment]
If it is no real extra effort I could possibly see a use case for that.

**Comment by eimann** [comment]
how many team members could use a radio during the event? would six radios be enough?

**Comment by jhilden** [comment]
6 would definitely be enough.

**Comment by eimann** [comment]
Ok, we'll bring them on Friday morning.

**Comment by jhilden** [comment]
sounds good. closing this
