### ISSUE TITLE
Veggi BBQ

### ISSUE THREAD

**Issue by tatjanala** [railscamp/railscamp-germany-2014#81]
Hey, is there anyone out there who wants to help organizing some veggi stuff for the bbq? Any suggestions what to put on the grill? Who can help prepare the food? @Mobbit @erdnusskeks

**Comment by martinotten** [comment]
When will the BBQ happen? If it is Saturday evening I cannot stay :( But I can certainly help to prepare something

**Comment by RmMsr** [comment]
Yes, it is on Saturday evening

**Comment by tatjanala** [comment]
Will will go BBQ shopping on Thursday afternoon, what should we bring? 
Thanks @Mobbit for helping!

**Comment by martinotten** [comment]
Aldi offers good and reasonable priced vegan/vegetarian BBQ supplies like sausages and steaks. Grilled vegetables would also be great. WDYT @erdnusskeks ?

**Comment by erdnusskeks** [comment]
@Mobbit, sounds good! I also like to grill: corn, zucchini, mushrooms. I could bring some marinade so it will be really delicious! : )

**Comment by tatjanala** [comment]
Hey, we bought vegetables (mushrooms, corn, zucchini, eggplant) and some vegetarian sausages. I hope it's enough, I don't know how many vegetarians will come...
