### ISSUE TITLE
Printing TODOs

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2014#82]
- **Sponsors**:  @erdnusskeks will create a PDF (A4) with all the sponsors and the names of the sponsor slots ("Captain Sponsors", ...)
- **Captain Sponsors**:  @tatjanala and @sloi will take care of bigger prints (something between A3 and A0 with "Captain Sponsor" + logo) for our 2 captains:  Railslove and Mailjet ([Mailjet assets](http://www.mailjet.com/system/asset_packages/packages/000/000/003/original/MailjetLogo.png.zip?1405334702)).  Those will be put right and left of the main stage.
- **Guest List**:  @m20io will print the latest eventbrite guest list on friday
- **Name Labels**:  @erdnusskeks can you create a document for that as well and I can try to print them on Etikettenpaper in the office

Anything else that needs to be printed?

**Comment by RmMsr** [comment]
- **Job Offerings**: [We received one till now](https://drive.google.com/#folders/0BxizCiVtZoVsTGJEYnhwaWtjeGs). Waiting for more
- [Burger sponsor Branding](https://docs.google.com/document/d/1Qqv0Tx5FchCG4MzgajPc65c1KnnBTkGHl8w_kR0gIZ8/edit#)

**Comment by erdnusskeks** [comment]
I also prepared a PDF with the previous sessions. With space for room and time.
![bildschirmfoto 2014-09-24 um 13 11 48](https://cloud.githubusercontent.com/assets/4786471/4387359/a19b1ce2-43db-11e4-87ce-f74375e446b9.png)

**Comment by erdnusskeks** [comment]
@jhilden: Name labels: a bit tricky but I will try. I use Open Office and I am not a pro working with that programme... What kind of Etikettenpapier do you have - how many columns, how many rows? Maybe you can name the serial number or something like that?

**Comment by jhilden** [comment]
> What kind of Etikettenpapier do you have - how many columns, how many rows? Maybe you can name the serial number or something like that?

@erdnusskeks its plain A4 Etikettenpapier with no rows/columns.  So you can format in whatever way you want.  I will also bring a Schneidemaschiene to cut them.

> I also prepared a PDF with the previous sessions. With space for room and time.

I personally would keep the session planning sheets more low-fi to save some work.  Here is a picture from jsunconf where it was also just plain paper:  https://plus.google.com/photos/+RobertKatzki/albums/6008004045204909217/6008004047705030818?pid=6008004047705030818&oid=102104213986872232697
