### ISSUE TITLE
Bringing a TV team on saturday....

### ISSUE THREAD

**Issue by nanoparsec** [railscamp/railscamp-germany-2014#83]
Hello,

the Rails Girls Berlin were asked if it's okay to bring a TV team to Railscamp on Saturday. 
They are producing a miniseries for the ARD about programmers and want also do an episode about Rails Girls.
I know this is very short before the camp (I am also surprised that they come back to me so late) but is there someone who I can connect to the TV guy?

All the best

Ute

**Comment by RmMsr** [comment]
There will be also a professional camera by one of our sponsors to catch impressions and record a talk on saturday. It should not be any problem. But if someone feels offended, we will ask to put the camera away.
