### ISSUE TITLE
Lost & Found

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2014#84]
Put in all the things that were found or lost during the camp in this issue

**Comment by jhilden** [comment]
I found @dhoelzgen's power adapter and this jacket seems to have been left: 
![2014-09-28 18 29 21](https://cloud.githubusercontent.com/assets/69657/4441341/a9070262-47d1-11e4-947b-f0d9978e3dd3.jpg)

**Comment by dhoelzgen** [comment]
Thanks @jhilden, @newmetl will visit you in your office soon and will grab it for me

**Comment by timoschilling** [comment]
@jhilden thats my jacket, please keep it in the railslove office until the next colognerb, THX

**Comment by jhilden** [comment]
@timoschilling I left the jacket at the Abenteuerhallen, because I wasn't sure that it belonged to Railscamp.  They have a lost & found there.  I'm afraid you will need to pick it up yourself unless somebody can do it for you.

**Comment by timoschilling** [comment]
@jhilden ok, THX

**Comment by nanoparsec** [comment]
My SoC partner Magda is missing her Pyjama. Have you found one?
