### ISSUE TITLE
Pics from 2014

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2014#85]
If you made pictures during this years Railscamp and are OK with sharing them with the world, please post them here:

https://www.dropbox.com/sh/8sln73dmyaaejtl/AABS1lUbG7ne_JwvlVd_dUS5a?dl=0 (from @tatjanala and @koos)

**Comment by klaustopher** [comment]
Video with some time-lapses from Saturday: https://www.youtube.com/watch?v=WybT9ORlUxY
